### DISCUSSION TITLE
ts-standard linting error

### DISCUSSION THREAD

**Discussion by mjonespro** [super-linter/super-linter#2745] [Q&A]
I have a typescript project I'm running super linter on locally. I consistently receive the same error below. I can only get it to go away when I turn off VALIDATE_TYPESCRIPT_STANDARD. It seems that eslint runs just fine on the typescript file. Is it safe to assume eslint linting will be enough if I leave typescript_standard disabled? I have created include blocks in my tsconfig file as well as a "ts-standard.project" block in my package.json file. It seems like none of the standard advice out there will get this error to resolve.

```
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard)
  /tmp/lint/projectName/projectFile.ts:0:0: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: projectName/projectFile.ts.
The file must be included in at least one of the projects provided. ()
```

**Comment by tncourtz** [comment]
Any chance you got this error to resolve? I'm getting a similar error. Not running locally but through github actions

**Reply by gmaiwald** [reply]
Same with me.

**Comment by Martin-Carlsson** [comment]
For people who found this issue while looking for a solution.

**How to disable `VALIDATE_TYPESCRIPT_STANDARD` like @mjonespro mentioned:**
Update the `.github/workflows/super-linter.yml`
```
# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_TYPESCRIPT_STANDARD: false
```
