### DISCUSSION TITLE
Black line-length in pyproject.toml is not recognized

### DISCUSSION THREAD

**Discussion by abhinovntap** [super-linter/super-linter#2923] [Q&A]
Hi Team,

We have a python project with pyproject.toml at the same directory level as ".github" and has specific lines:
[tool.black]
line-length = 120

Black runs locally(on a personal computer) by recognizing the pyproject.toml and align code to 120 chars. When configured with a github action for super-linter, black fails to recognize the line-length in pyproject.toml and defaults to 88 chars.

There are no other files that have black rules defined, Do I have to explicitly configure a new file under TEMPLATES with "line-length" = 120 ?

My linter.yml files has the below snippet
```

################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
