### DISCUSSION TITLE
Can't get the linter working in my qa branch

### DISCUSSION THREAD

**Discussion by YasmenW** [super-linter/super-linter#6704] [Q&A]
I've been asked to add the Super Linter to our project. I started with the qa branch, committed my .yml file as indicated in the docs. I keep getting the workflow failing after 3 mins with the following error: `2025-03-28 15:18:09 [FATAL]   Failed to run composer install for /github/workspace. Output: Your lock file does not contain a compatible set of packages. Please run composer update.`
I've tried composer install, composer update, deleting the lock file and regenerating it. I also tried specifying a PHP version in my file and nothing seems to work. I've been hitting my head against the wall and any help would be appreciated!  I'm sharing my file here:

```
`name: Linter 

on: # yamllint disable-line rule:truthy
  push: 
   branches:
       - qa
  pull_request: 
   branches:
       - qa

permissions: {}

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
```
```

**Comment by ferrarimarco** [comment]
In Super-linter v7.3.0, we updated PHP to 8.4.

In the `latest` version, we just merged a pull request (#6637) that shows composer output, so you can actually understand what's happening.

Can you try switching to `latest`, instead of `v.7.3.0`? Once `v7.4.0` is released, you should switch to that instead.

**Comment by YasmenW** [comment]
Do you mean I should upgrade my PHP version as well? I modified my script to use the latest and I'm still getting the same error =>

```

  ` jobs:
     build:
      name: Lint
     runs-on: ubuntu-latest  

    permissions: 
      contents: read
      packages: read
      statuses: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@latest 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` 
```

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/3a789f30-3c34-4415-a3bd-dc42c470c099" />
