### ISSUE TITLE
YAML_CONFIG_FILE not working as expected 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [super-linter/super-linter#3914]
according to https://github.com/marketplace/actions/super-linter the YAML_CONFIG_FILE default is `.yaml-lint.yml` but according to https://yamllint.readthedocs.io/en/stable/configuration.html the files could be `.yamllint`, `.yamllint.yaml`, or `.yamllint.yml`.

I tried to use `.yamllint.yml` and i switched to `.yaml-lint.yml` in the github ci check but it is failing to pick up the right configuration file.  I am trying this out in https://github.com/buildtesters/buildtest/pull/1385. Dont mind the other changes i am trying to fix. Basically i want to see the path to configuration file used since its not clear to me. IT is not using the one i have committed in the project because i ran `yamllint` locally and it was giving different results than what i am seeing in CI check.

**Comment by shahzebsiddiqui** [comment]
in particular the failure is https://github.com/buildtesters/buildtest/actions/runs/4148181155/jobs/7175912016 i am looking at some of the warning messages like this

```
Warning: orkspace/.github/workflows/jsonschemadocs.yml:1:1: [warning] missing document start "---" (document-start)
Warning: orkspace/.github/workflows/jsonschemadocs.yml:14:5: [warning] wrong indentation: expected 6 but found 4 (indentation)
```

i tried this locally and i am not getting the same error

```
(buildtest)  ~/Documents/github/buildtest/ [superlinter] yamllint -c .yaml-lint.yml .github/workflows/jsonschemadocs.yml 
.github/workflows/jsonschemadocs.yml
  3:1       warning  truthy value should be one of [false, true]  (truthy)

```

**Comment by jonesy1234** [comment]
I'm also experiencing this, can't get the yamllint exclude file parsed or even recognised. This is regardless to overriding the default config file name via an env variable.

**Comment by slavazais-auchan** [comment]
Same here, 

I've put one file pattern to ignore it, but it still doesn't work with `super-linter`, while it's working perfectly with `yamllint` itself.

yaml-lint.yml
```yaml
ignore:
  - '*wrong_yaml_format.yaml'

rules: ...
```

super-linter result:
```text
2023-04-04 15:35:54 [ERROR]   Found errors in [yamllint] linter!
2023-04-04 15:35:54 [ERROR]   Error code: 255. Command output:
------
invalid config: ignore should contain file patterns
------
```

yamllint (from pip)
```shell
yamllint -c .github/linters/.yaml-lint.yml wrong_yaml_format.yaml
```
return nothing and a code 0

**Comment by megamorf** [comment]
This is still an issue, super-linter is actively ignoring the ignore section of the yamllint config, e.g.:

```yaml
---
extends: default
rules:
  line-length: disable
  truthy: disable
  comments: disable

# https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths
ignore: |
  /application-*.yml
```

Given that config and the following command, `application-*.yml` files in the root of my repository are excluded by yamllint:

```sh
$ yamllint -c .yamllint.yaml --list-files .

./.yamllint.yaml
./.markdownlint.yaml
./actionlint.yaml
./.github/workflows/manual-deploy.yml
./.github/workflows/check-yq.yml
./.github/workflows/ci.yml
./.github/actions/update-image-tag/action.yml
./.github/test-samples/yq/kustomization-original.yaml
./.github/test-samples/yq/kustomization-expected.yaml
./base/kustomization.yaml
./base/resources/poddisruptionpolicy.yaml
./base/resources/deployment.yaml
./base/resources/secrets.yaml
./base/resources/ingress.yaml
./base/resources/service.yaml
./base/resources/gatewayservice.yaml
./base/resources/s3-mediastorage.yaml
./base/resources/envvars.yaml
```

This even works with: 

```
docker run --rm -e RUN_LOCAL=true  -e LINTER_RULES_PATH="/" -e VALIDATE_YAML="true" -e YAML_CONFIG_FILE=".yamllint.yaml"  -v $(pwd):/tmp/lint ghcr.io/github/super-linter:slim-v4.10.0
```

However, when run as action like this it reports errors for the excluded files:

```yaml
jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter/slim@v4
        env:
          GITHUB_DOMAIN: ${{ secrets.GHES_DOMAIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          LINTER_RULES_PATH: /
          YAML_CONFIG_FILE: .yamllint.yaml
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
```
