### ISSUE TITLE
Passing custom config to KubeConform does not seem to be working locally via Docker

### ISSUE THREAD

**Issue by invalidred** [super-linter/super-linter#3978]
Hello!

### Context
I have a git-ops repo that contains k8s `.yaml` files and helm (non templated filed) in `Chart.yaml` and `values.yaml`. The k8s uses CRD such as ArgoApplication, ExternalSecrets etc...

When I run kueconform locally which includes linking to CRD and ignore `Chart.yaml` and `values.yaml`, I get no errors

```bash
kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern Chart.yaml -ignore-filename-pattern values.yaml  .
```

However when I pass the same config to super linter locally I get **9 Kubeconform** errors.

```
docker run  \
 -e RUN_LOCAL=true \
 -e USE_FIND_ALGORITHM=true \
 -e KUBERNETES_KUBECONFORM_OPTIONS="-schema-location=default -schema-location='https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern=Chart.yaml -ignore-filename-pattern=values.yaml" \
 -e YAML_ERROR_ON_WARNING=true \
 -v /Users/abdulkhan/github/git-ops:/tmp/lint \
 github/super-linter
```

I have tried passing various combination to the `-e KUBERNETES_KUBECONFORM_OPTIONS` 

```
- -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern Chart.yaml -ignore-filename-pattern values.yaml /tmp/lint
- -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern Chart.yaml -ignore-filename-pattern values.yaml
- -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern Chart.yaml -ignore-filename-pattern values.yaml .
- -schema-location=default -schema-location='https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -ignore-filename-pattern=Chart.yaml -ignore-filename-pattern=values.yaml
```

How do I pass custom config to kubeconfirm via Docker? I am doing something wrong and would appreciate some help.

**Comment by deltabrot** [comment]
It seems #3800 hasn't been included in the latest tag as of today (v4.10.1). This means that in practice super-linter is still using KUBEVAL under the hood.

I have tried to use the latest commit as a tag in my workflow:
```yaml
---
name: Super Linter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  build:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Lint Code Base
        uses: github/super-linter@e954bee85d84e8ca866c1e14d2bf33e555d85d9b
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
```

But for some reason the action still pulls version v4.10.1.

**Comment by mdfaizsiddiqui** [comment]
> It seems #3800 hasn't been included in the latest tag as of today (v4.10.1). This means that in practice super-linter is still using KUBEVAL under the hood.
> 
> I have tried to use the latest commit as a tag in my workflow:
> 
> ```yaml
> ---
> name: Super Linter
> 
> on:
>   pull_request:
>     types: [opened, edited, reopened, synchronize, ready_for_review]
> 
> jobs:
>   build:
>     name: Super Linter
>     runs-on: ubuntu-latest
> 
>     steps:
>       - name: Checkout Code
>         uses: actions/checkout@v3
>         with:
>           # Full git history is needed to get a proper
>           # list of changed files within `super-linter`
>           fetch-depth: 0
> 
>       - run: cat .github/super-linter.env >> "$GITHUB_ENV"
> 
>       - name: Lint Code Base
>         uses: github/super-linter@e954bee85d84e8ca866c1e14d2bf33e555d85d9b
>         env:
>           VALIDATE_ALL_CODEBASE: false
>           DEFAULT_BRANCH: main
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
> ```
> 
> But for some reason the action still pulls version v4.10.1.
> 
> This is frustrating because the documentation in the super-linter README.md is not synchronised with the version actually being used.

I'm facing the same problem!

**Comment by reefland** [comment]
@invalidred - you still have this issue?  I'm trying with version 5.0.0 and get same results with Github:

```
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          # KUBERNETES_KUBECONFORM_OPTIONS: "--ignore-missing-schemas"
          # KUBERNETES_KUBECONFORM_OPTIONS: "--schema-location default --schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'"
          KUBERNETES_KUBECONFORM_OPTIONS: "-schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'"
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If I use the `"--ignore-missing-schemas"` no errors, if I try to use the CRDs it fails:
```
2023-05-03 20:47:38 [INFO]   Linting [KUBERNETES_KUBECONFORM] files...
2023-05-03 20:47:38 [INFO]   ----------------------------------------------
2023-05-03 20:47:38 [INFO]   ----------------------------------------------
2023-05-03 20:47:38 [INFO]   ---------------------------
2023-05-03 20:47:38 [INFO]   File:[/github/workspace/applications/cert-manager.yaml]
2023-05-03 20:47:38 [ERROR]   Found errors in [kubeconform] linter!
2023-05-03 20:47:38 [ERROR]   Error code: 1. Command output:
------
/github/workspace/applications/cert-manager.yaml - Application cert-manager failed validation: could not find schema for Application
```
