### ISSUE TITLE
allow to pass custom flags to rust:clippy

### ISSUE THREAD

**Issue by smallstepman** [super-linter/super-linter#4001]
**Is your feature request related to a problem? Please describe.**
In our current rust linting GHA workflow we're running clippy by issuing the following command: `cargo clippy --verbose --tests --benches -- -D clippy::all`.

**Describe the solution you'd like**
Add ENVVAR to super-linter: `CLIPPY_FLAGS`, so I could set it like this:
```yml
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          CLIPPY_FLAGS: "--verbose --tests --benches -- -D clippy::all"
```

**Describe alternatives you've considered**
not sure

**Additional context**
N/A
