### ISSUE TITLE
TERRAFORM_TFLINT_CONFIG_FILE doesn't work as expected

### ISSUE THREAD

**Issue by pasdam** [super-linter/super-linter#4232]
## Describe the bug

SuperLinter github action doesn't read the `tflint` config file path correctly, it seems like it ignore the path specified with the env variable, or it's only using the filename, but not the whole absolute path.

## Expected behavior

SuperLinter should use the exact path as specified in the env variable.

## Steps to Reproduce

1. use this step in a workflow job
  ```yaml
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFLINT_LOG: debug
          TERRAFORM_TFLINT_CONFIG_FILE: ${{ github.workspace }}/.tflint.custom.hcl
  ```
2. run the workflow

## Logs

From the workflow run logs, the input is:

```
TERRAFORM_TFLINT_CONFIG_FILE: /home/runner/work/my-repo/my-repo/.tflint.custom.hcl
```

but then `tflint` fails with:

```text
2023-05-23 03:26:24 [INFO]   Gathering user validation information...
2023-05-23 03:26:24 [INFO]   - Only validating [new], or [edited] files in code base...
2023-05-23 03:26:27 [FATAL]     -> TERRAFORM_TFLINT_LINTER_RULES rules file (/action/lib/.automation//github/workspace/.tflint.custom.hcl) doesn't exist. Terminating...
```
