### ISSUE TITLE
Huh?  You are not currently on a branch

### ISSUE THREAD

**Issue by woodconn** [super-linter/super-linter#4361]
How do I get it to see the pull request is on a branch....

I've tried DEFAULT_BRANCH with multiple values but I keep getting the same **You are not currently on a branch.**
I've tried with:
- master
- main
- '*'
- ${{ github.ref }}
- ${{ github.head_ref }}

> 2023-06-07 21:01:54 [INFO]   Gathering user validation information...
> 2023-06-07 21:01:54 [INFO]   - Only validating [new], or [edited] files in code base...
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>

Configuration:
```
    - name: Run Super Linter
      uses: super-linter/super-linter/slim@v5
      env:
        VALIDATE_ALL_CODEBASE: false # When false, only new or edited files will be parsed for validation.
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_TYPESCRIPT_STANDARD: true
        VALIDATE_JAVASCRIPT_STANDARD: true
        VALIDATE_JSON: true
        VALIDATE_HTML: true
        # for more info see: https://github.com/super-linter/super-linter#environment-variables
```
