### ISSUE TITLE
Super Linter not picking up default config file for YAML_LINT

### ISSUE THREAD

**Issue by hsachan22** [super-linter/super-linter#4377]
## Describe the bug

I created a file with name `.yaml-lint.yml` and defined some custom rules, but super linter is not using this custom file for linting yaml files.

## Expected behavior

I want it use my custom config file.

## Steps to Reproduce

```bash
docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=. \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -e YAML_CONFIG_FILE=.yaml-lint.yml \
  -v $(pwd):/tmp/lint \
  ghcr.io/github/super-linter:slim-v4.10.0
```

**Comment by gmacario** [comment]
Ping

**Comment by gmacario** [comment]
Ping

**Comment by evandam** [comment]
Seeing this issue as well. Tried using the default `.yaml-lint.yml` as documented in the readme and setting `YAML_CONFIG_FILE: .yaml-lint.yml` but neither seem to do anything.

**Comment by ferrarimarco** [comment]
In the example you posted in https://github.com/super-linter/super-linter/issues/4377#issue-1762952922, you're setting both the `YAML_CONFIG_FILE=.yaml-lint.yml` and the `LINTER_RULES_PATH=.` variables. This means that super-linter will look in `./.yaml-lint.yml` for the yamllint rules file, where `.` is the root of your repository. This is documented here: https://github.com/super-linter/super-linter/blob/main/docs/using-rules-files.md

Is there such a file there?

**Comment by ferrarimarco** [comment]
Also, posting the relevant parts of the debug log would help.

**Comment by gmacario** [comment]
Please keep it open

**Comment by gmacario** [comment]
Please keep it open

**Comment by ferrarimarco** [comment]
This is working for me and others. Without further details (minimal reproduction, debug log...) we can't help further.

**Comment by neilime** [comment]
Hi,

YAML_CONFIG_FILE is still not working. 

@ferrarimarco Here are some simple a reproduction ways:

## First case:

Create a config file `.github/linters/.yaml-lint.yml`  - Deliberately erroneous

```yml
extends: default

wrong
```

Run the CI, you should have an error like invalid config: mapping values are not allowed here, but you will not as it does not use the config file

## Second case: force absolute path of config file

```yml
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE="/github/workspace/.github/linters/.yaml-lint.yml"
```

You will have the following error: `YAML_LINTER_RULES rules file (/action/lib/.automation//github/workspace/.github/linters/.yaml-lint.yml) doesn't exist.`

## Workaround:

Set relative path (from `/action/lib/.automation`)

```yml
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE="../../../github/workspace/.github/linters/.yaml-lint.yml"
```
