### ISSUE TITLE
[Feature Request] Add configuration for overriding the image registry repository

### ISSUE THREAD

**Issue by ciandt-crodrigues** [super-linter/super-linter#4413]
**Is your feature request related to a problem? Please describe.**
My github pipeline has limited internet access and our images only comes from our internal container registry. So the pipeline always fails on pulling the image

**Describe the solution you'd like**
I would like to introduce a new config option or environment variable to override the image repository so I can point to my image on our repository which is scanned for vulnerabilities with our rules

**Describe alternatives you've considered**
N/A

**Comment by zkoppert** [comment]
I believe that you can override the image registry right in the action definition like this where ghcr.io can be your custom container registry url:

```yaml
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:latest
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
