### ISSUE TITLE
Add `CUSTOM_SCRIPT` environment variables

### ISSUE THREAD

**Issue by smallstepman** [super-linter/super-linter#4525]
for example
```yml
- name: Lint Code Base
  uses: super-linter/super-linter/slim@v5
  env:
    VALIDATE_ALL_CODEBASE: false
    CUSTOM_SCRIPT: custom_script.sh
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
This would allow the users of this action to customize the running docker image (install new dependencies, add/swap linters)
