### ISSUE TITLE
Getting  No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!

### ISSUE THREAD

**Issue by andrewakl** [super-linter/super-linter#4558]
Hi.

I'm not sure why I'm getting `No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!` .

This is what i have:

```
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Am i missing something?
