### ISSUE TITLE
Automate some dependency updates

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#4647]
**Is your feature request related to a problem? Please describe.**

Given that most PRs are about dependency updates, and that we have a relatively comprehensive test suite out there, it would be useful to automatically approve and merge the dependency updates that we consider safe. That would let us focus on more interesting PRs.

**Describe the solution you'd like**

A relatively simple GitHub Actions job such as the following:

```
---
name: Dependabot automation

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR
        run: gh pr review --approve "${PR_URL}"
      - name: Enable auto-merge for patch updates PR
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
          || steps.metadata.outputs.dependency-names == 'actions/checkout'
          || steps.metadata.outputs.dependency-names == 'docker/metadata-action'
        run: gh pr merge --auto --squash --delete-branch "${PR_URL}"
...
```

In this example, we  automatically merge patch updates for any dependency, and any update for the `actions/checkout` and  `docker/metadata-action`.

Thoughts?
