### ISSUE TITLE
Docker builds have run out of space

### ISSUE THREAD

**Issue by zkoppert** [super-linter/super-linter#4735]
## Describe the bug

See log example at https://github.com/super-linter/super-linter/actions/runs/6515632583/job/17698280121#step:7:93

**Comment by zkoppert** [comment]
CI on even documentation changes are going to fail at this point until this is resolved.

**Comment by nvuillam** [comment]
Hi neighbor ! :)

We had the same issue, that you can solve by removing useless stuff from default runner

```yml
      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
```
