### ISSUE TITLE
Add back container image labels tests and remove obsolete scripts

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#4895]
**Is your feature request related to a problem? Please describe.**
We are currently missing labels check. We used to have them. This got lost when reworking workflows.

Also, `.automation/cleanup-docker.sh` and `.automation/upload-docker.sh` are probably not needed anymore because we handle that with workflows now. Wanted to check before cleaning up.

**Describe the solution you'd like**

```yaml
      - name: Run container image label test cases
        if: ${{ github.repository == 'github/super-linter' && github.ref != 'refs/heads/main' }}
        shell: bash
        run: .automation/validate-docker-labels.sh "${{ matrix.images.image-id }}"
```

Also, remove obsolete scripts.

@zkoppert WDYT?
