### ISSUE TITLE
upgrade docs- workflow yaml must change; @v6 doesn’t work, @v6.0.0 does

### ISSUE THREAD

**Issue by mobilemind** [super-linter/super-linter#5224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Previously this worked (and continues to work), but now there seems to be multiple issues with upgrades from v5 to v6, that aren’t covered in the upgrade docs.

If one merely changes the major version number from this working code there are multiple issues
```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: github/super-linter/slim@v5
```

Case 1: Fails because of the repo owner/path hasn’t been changed (Note **github**/super-linter)

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: github/super-linter/slim@v6
```

Case 2: May fail due to settings on the user’s repo, even though path is now correct. Maybe docs can reference need to change settings in user’s repo to trust super-linter or Marketplace??

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: super-linter/super-linter/slim@v6
```

Case 3: with permissions adjusted, this “upgrade” still fails because super-linter now seems to require a full semver number, to run v6

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: super-linter/super-linter/slim@v6
```
 It currently seems like repo owners must use this:

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: super-linter/super-linter/slim@v6.0.0
```

### Expected Behavior

Upgrade should indicate changes required to workflow yaml, such as:

When upgrading from v5 to v6, you must update the super-linter specification path and include a full semver number in your workflow, and super-linter must be a trusted workflow in the repo’s Settings > Actions > General.

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: github/super-linter/slim@v5
```

becomes

```yml
      # Run Linter against code base
      - name: Lint Code Base with env
        uses: super-linter/super-linter/slim@v6.0.0
```
