### ISSUE TITLE
super-linter v6 doesn't work with pull request

### ISSUE THREAD

**Issue by tremblaysimon** [super-linter/super-linter#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using super-linter in a workflow run triggered by a **pull request**, there is a FATAL error message like this one: 

```
  2024-02-21 11:38:08 [INFO]   --------------------------------------------
  2024-02-21 11:38:08 [INFO]   Gathering GitHub information...
  2024-02-21 11:38:08 [INFO]   Successfully validated GITHUB_WORKSPACE: /github/workspace
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_EVENT_PATH: /github/workflow/event.json]
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_SHA: a076f27a559fbd3aeb95f5a9810665a2db829d39
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_ORG: (redacted)
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_REPO: (redacted)
  2024-02-21 11:38:08 [INFO]   The default branch for this repository is set to: main
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_TOKEN.
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_REPOSITORY: (redacted)
  2024-02-21 11:38:08 [INFO]   Successfully found GITHUB_RUN_ID 7988363078
  2024-02-21 11:38:08 [INFO]   --------------------------------------------
  2024-02-21 11:38:08 [INFO]   Validating the configuration
  .git
  2024-02-21 11:38:08 [FATAL]   The GITHUB_SHA reference (e56d1cfc9976e77d47de6eae7480689a2aefb0d4) doesn't exist in this Git repository
```

The `actions/checkout` doesn't have specific parameters set. I found that breaking change #4889 could be related to that error but in the end I don't figure out what `ref` parameter I should use in `actions/checkout` to satisfy super-linter action in a pull request. 

The `actions/checkout` does a merge commit by default when it's used in a pull request workflow run. Maybe it's related to that behavior. But honestly I don't figure out what to put in `ref` parameter or other things to do to make it work.

### Expected Behavior

Super-linter action should work inside a pull request workflow run or at least there should be documentation about how to make it works.

### Super-Linter version

```markdown
v6.2.0
```

#### Checkout log

```shell
Temporarily overriding HOME='/runner/_work/_temp/2780ebbb-1909-4ff5-8aad-02d4e7e0a263' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /runner/_work/redacted/redacted
Deleting the contents of '/runner/_work/redacted/redacted'
Initializing the repository
Disabling automatic garbage collection
Setting up auth
Fetching the repository
Determining the checkout info
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/54/merge
  Note: switching to 'refs/remotes/pull/54/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at a076f27 Merge e56d1cfc9976e77d47de6eae7480689a2aefb0d4 into bcbf0667cb[40](https://github.com/redacted/actions/runs/7988363078/job/21812774610#step:4:44)932706036184aba6cbd[54](https://github.com/redacted/actions/runs/7988363078/job/21812774610#step:4:61)4d67e17
/usr/bin/git log -1 --format='%H'
'a076f27a[55](https://github.com/redacted/actions/runs/7988363078/job/21812774610#step:4:62)9fbd3aeb95f5a98106[65](https://github.com/redacted/actions/runs/7988363078/job/21812774610#step:4:72)a2db829d39'
```

### Steps To Reproduce

1. Create a workflow that uses super-linter and triggers on a pull request event
2. Create a pull request
3. Observe a super-linter error like this one: `[FATAL]   The GITHUB_SHA reference (e56d1cfc9976e77d47de6eae7480689a2aefb0d4) doesn't exist in this Git repository`

**Comment by ferrarimarco** [comment]
Hi @tremblaysimon !

Can you share the configuration of the workflow that runs super-linter? I suspect that the checkout code didn't fetch the whole history as [explained in the README](https://github.com/super-linter/super-linter?tab=readme-ov-file#get-started).

**Comment by tremblaysimon** [comment]
Hello @ferrarimarco, you're right. Our workflow was missing `fetch-depth: 0` for the `actions/checkout` action. I should have read more carefully your documentation. Sorry about that! 

Maybe I was confused because I didn't see #5096 as a breaking change in the [v6.0.0](https://github.com/super-linter/super-linter/releases/tag/v6.0.0) release notes even if it was checked in the PR description (but the label `breaking` is missing). Maybe it should be moved in the Breaking changes section of the release notes since it contains the modified README where we clearly see now we need to add `fetch-depth: 0` in checkout action. Does it make sense?

Thank you for everything, very useful action for us!

**Comment by ferrarimarco** [comment]
Thanks!

IIRC, that check was implemented in #4889, which is classified as breaking :)

:)

**Comment by tremblaysimon** [comment]
I agree with you, but in #4889 it's not explicit that we need to fetch the entire history. I added a comment to make it more explicit! :)

**Comment by sebastian-fredriksson-bernholtz** [comment]
I don't understand why superlinter needs the whole history for pull requests? The referenced commit in a pull request is specifically the changes that the pull request results in when merging to the target branch, the changes that should be linted?

The fact that https://github.com/super-linter/super-linter/pull/4889 makes superlinter abort because it thinks that the commit doesn't exist seems like a bug. The commit does exist, it's just not immediately accessible because it's only referenced by the special github `refs/pull/<pr_number>/merge` reference.

We have a large monorepo and checking out the full history is very inefficient. We've ended up hacking the checkout to get superlinter what it needs, without having to check the entire history. But it's a bit annoying because github already does all the work for us and superlinter, just that superlinter doesn't use it?

<details><summary>Our hack:</summary>

```yaml
    steps:
      - name: Compare branch to main
        if: github.ref  != 'refs/heads/main'
        id: compare_commits
        run: |-
          CC=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ourOrg/ourRepo/compare/main...${{ github.sha }})
          echo "fetch_from_branch=$(($(echo $CC | jq '.ahead_by')+1))" >> $GITHUB_OUTPUT
          echo "fetch_from_trunk=$(($(echo $CC | jq '.behind_by')+1))" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Checkout branch
        if: github.ref  != 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ steps.compare_commits.outputs.fetch_from_branch }}
      - name: Fetch main for comparison
        if: github.ref  != 'refs/heads/main'
        run: git fetch origin main:main --depth ${{ steps.compare_commits.outputs.fetch_from_trunk }}
      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_ACTIONS_COMMAND_ARGS: -ignore 'Double quote to prevent globbing and word splitting'
```

</details>
