### ISSUE TITLE
Super-linter actions fails without error

### ISSUE THREAD

**Issue by kaefferlein** [super-linter/super-linter#5335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running a github action with the super-linter v6 and want a successful run. Yet it fails but states no error message. It just stops after the log message `Building the list of files and directories to check`.
The action job is marked as failed.

### Expected Behavior

Successful run or error message

### Super-Linter version

```markdown
v6.2.0
```

### Relevant log output

```shell
Super-Linter initialization
  --------------------------------------------------------------------------------
                                /@@#///////@@/(@//@%/(@.@(       @@
                            @@//////////////////////////////#*  @@@
                          @////@//(///////////@@@@@///@//@/@**//@@(
                        @///////@///////////////@@@@    (           @,
                       @/(&/@////////////////////                     @
                      @////////////////////////@@                      @
                    @%////////(//////////%/////&@            @@       *,@           ______________
               @@@@@/@/#/////(&//////////////////                       .@         /              \
          *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
        @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
      @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
  @@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
                                            @@@/@(  (@@@@% @/\      %
                                             @@@@(    .     .@@/\   #
                                               @                  %@%
  --------------------------------------------------------------------------------
  2024-02-27 09:54:46 [INFO]   ---------------------------------------------
  2024-02-27 09:54:46 [INFO]   --- GitHub Actions Multi Language Linter ----
  2024-02-27 09:54:46 [INFO]    - Image Creation Date: 2024-02-20T21:39:00Z
  2024-02-27 09:54:46 [INFO]    - Image Revision: 25003d0370b45d97187597838ecb9fdadfc08aea
  2024-02-27 09:54:46 [INFO]    - Image Version: 25003d0370b45d97187597838ecb9fdadfc08aea
  2024-02-27 09:54:46 [INFO]   ---------------------------------------------
  2024-02-27 09:54:46 [INFO]   ---------------------------------------------
  2024-02-27 09:54:46 [INFO]   The Super-Linter source code can be found at:
  2024-02-27 09:54:46 [INFO]    - https://github.com/super-linter/super-linter
  2024-02-27 09:54:46 [INFO]   ---------------------------------------------
  2024-02-27 09:54:46 [INFO]   - Validating changed files in code base...
  chktex: chktex: WARNING -- Could not find global resource file.
  ChkTeX v1.7.8 - Copyright 1995-96 Jens T. Berger Thielemann.
  Compiled with POSIX extended regex support.
  rubocop: 1.60.2
  perl: 
  This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-thread-multi
  Copyright 1987-2023, Larry Wall
  Perl may be copied only under the terms of either the Artistic License or the
  GNU General Public License, which may be found in the Perl 5 source kit.
  Complete documentation for Perl, including FAQ lists, should be found on
  this system using "man perl" or "perldoc perl".  If you have access to the
  Internet, point your browser at https://www.perl.org/, the Perl Home Page.
  xmllint: xmllint: using libxml version 21106
     compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 HTTP DTDValid HTML C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Schemas Schematron Modules Debug Zlib Lzma 
  ansible-lint: ansible-lint 24.2.0 using ansible-core:2.16.3 ansible-compat:4.1.11 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
  eslint: v8.56.0
  markdownlint: 0.39.0
  snakefmt: snakefmt, version 0.10.0
  cpplint: Cpplint fork (https://github.com/cpplint/cpplint)
  cpplint 1.6.1
  Python 3.12.2 (main, Feb  7 2024, 22:13:24) [GCC 13.2.1 20231014]
  editorconfig-checker: 2.7.2
  gitleaks: v8.18.2
  phpstan: PHPStan - PHP Static Analysis Tool 1.10.48
  dotenv-linter: dotenv-linter 3.3.0
  asl-validator: 3.8.2
  actionlint: 1.6.26
  installed by building from source
  built with go1.21.1 compiler for linux/amd64
  tekton-lint: 1.0.0-beta.9
  terrascan: version: v1.18.11
  terraform: Terraform v1.7.3
  on linux_amd64
  2024/02/20 18:33:30 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
  2024/02/20 18:33:30 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
  clippy: clippy 0.1.72
  R: R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
  Copyright (C) 2023 The R Foundation for Statistical Computing
  Platform: x86_64-pc-linux-musl (64-bit)
  R is free software and comes with ABSOLUTELY NO WARRANTY.
  You are welcome to redistribute it under the terms of the
  GNU General Public License versions 2 or 3.
  For more information about these matters see
  https://www.gnu.org/licenses/.
  rustfmt: rustfmt 1.6.0-stable ( )
  shellcheck: ShellCheck - shell script analysis tool
  version: 0.9.0
  license: GNU General Public License, version 3
  website: https://www.shellcheck.net
  jscpd: 3.5.10
  black: black, 24.2.0 (compiled: no)
  Python (CPython) 3.12.2
  prettier: 3.2.5
  php: PHP 8.2.15 (cli) (built: Jan 18 2024 16:40:05) (NTS)
  Copyright (c) The PHP Group
  Zend Engine v4.2.15, Copyright (c) Zend Technologies
  textlint: v14.0.3
  npm-groovy-lint: GroovyLint: Successfully processed CodeNarc: 
  CodeNarc version 3.3.0
  dart: Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
  isort: 
                   _                 _
                  (_) ___  ___  _ __| |_
                  | |/ _/ / _ \/ '__  _/
                  | |\__ \/\_\/| |  | |_
                  |_|\___/\___/\_/   \_/
        isort your imports, so you don't have to.
                      VERSION 5.13.2
  dotnet: 8.0.101
  eslint: v8.56.0
  rustfmt: rustfmt 1.6.0-stable ( )
  htmlhint: 1.1.4
  rustfmt: rustfmt 1.6.0-stable ( )
  sql-lint: 1.0.0
  checkov: 3.2.22
  lua: Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
  standard: 17.1.0
  2024-02-27 09:54:46 [INFO]   --------------------------------------------
  2024-02-27 09:54:46 [INFO]   Gathering GitHub information...
  2024-02-27 09:54:46 [INFO]   Successfully validated GITHUB_WORKSPACE: /github/workspace
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_EVENT_PATH: /github/workflow/event.json]
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_SHA: <MY_SHA>
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_ORG: <MY_ORG>
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_REPO: <MY_REPO>
  2024-02-27 09:54:46 [INFO]   The default branch for this repository is set to: master
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_TOKEN.
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_REPOSITORY: <MY_ORG>/<MY_REPO>
  2024-02-27 09:54:46 [INFO]   Successfully found GITHUB_RUN_ID 8062771487
  2024-02-27 09:54:46 [INFO]   --------------------------------------------
  2024-02-27 09:54:46 [INFO]   Validating the configuration
  .git
  2024-02-27 09:54:47 [INFO]   The master branch doesn't exist in /github/workspace
  <SHA>
  2024-02-27 09:54:47 [INFO]   master doesn't exist, however origin/master exists. Setting DEFAULT_BRANCH to: origin/master
  2024-02-27 09:54:50 [INFO]   Building the list of files and directories to check
```

### Steps To Reproduce

1. create a github action workflow:
 ```
 name: Lint GitHub Action Workflows

on: pull_request

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_ANSIBLE: false
          FILTER_REGEX_EXCLUDE: .*/actions/link-checker-for-mms-gh-repos/dist/.*.js
          KUBERNETES_KUBECONFORM_OPTIONS: "-verbose -schema-location https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json"

 ```

2.  create a PR and check the linter
