### ISSUE TITLE
Error when building the list of files and directories to lint

### ISSUE THREAD

**Issue by stefenAMZ** [super-linter/super-linter#5341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when upgrade from v5 to v6 the linter is now throwing fatal errors when linting go files.

### Expected Behavior

Linting to not throw fatal errors.

### Super-Linter version

```markdown
v6.3.0
```

### Relevant log output

```shell
Run super-linter/super-linter@v6
/usr/bin/docker run --name ghcriosuperlintersuperlinterv630_68b4ef --label a8f055 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/terraform-provider/terraform-provider":"/github/workspace" ghcr.io/super-linter/super-linter:v6.3.0
Super-Linter initialization
  --------------------------------------------------------------------------------
  
                                /@@#///////@@/(@//@%/(@.@(       @@
                            @@//////////////////////////////#*  @@@
                          @////@//(///////////@@@@@///@//@/@**//@@(
                        @///////@///////////////@@@@    (           @,
                       @/(&/@////////////////////                     @
                      @////////////////////////@@                      @
                    @%////////(//////////%/////&@            @@       *,@           ______________
               @@@@@/@/#/////(&//////////////////                       .@         /              \
          *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
        @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
      @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
  @@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
                                            @@@/@(  (@@@@% @/\      %
                                             @@@@(    .     .@@/\   #
                                               @                  %@%
  
  --------------------------------------------------------------------------------
  2024-02-29 15:36:59 [INFO]   ---------------------------------------------
  2024-02-29 15:36:59 [INFO]   --- GitHub Actions Multi Language Linter ----
  2024-02-29 15:36:59 [INFO]    - Image Creation Date: 2024-02-29T07:13:31Z
  2024-02-29 15:36:59 [INFO]    - Image Revision: e0fc164bba85f4b58c6cd17ba1dfd435d01e8a06
  2024-02-29 15:36:59 [INFO]    - Image Version: e0fc164bba85f4b58c6cd17ba1dfd435d01e8a06
  2024-02-29 15:36:59 [INFO]   ---------------------------------------------
  2024-02-29 15:36:59 [INFO]   ---------------------------------------------
  2024-02-29 15:36:59 [INFO]   The Super-Linter source code can be found at:
  2024-02-29 15:36:59 [INFO]    - https://github.com/super-linter/super-linter
  2024-02-29 15:36:59 [INFO]   ---------------------------------------------
  2024-02-29 15:36:59 [INFO]   - Validating all files in code base...
  chktex: chktex: WARNING -- Could not find global resource file.
  ChkTeX v1.7.8 - Copyright 1995-96 Jens T. Berger Thielemann.
  Compiled with POSIX extended regex support.
  rubocop: 1.60.2
  perl: 
  This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-thread-multi
  
  Copyright 1987-2023, Larry Wall
  
  Perl may be copied only under the terms of either the Artistic License or the
  GNU General Public License, which may be found in the Perl 5 source kit.
  
  Complete documentation for Perl, including FAQ lists, should be found on
  this system using "man perl" or "perldoc perl".  If you have access to the
  Internet, point your browser at https://www.perl.org/, the Perl Home Page.
  xmllint: xmllint: using libxml version 21106
     compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 HTTP DTDValid HTML C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Schemas Schematron Modules Debug Zlib Lzma 
  ansible-lint: ansible-lint 24.2.0 using ansible-core:2.16.4 ansible-compat:4.1.11 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
  eslint: v8.57.0
  markdownlint: 0.39.0
  snakefmt: snakefmt, version 0.10.0
  cpplint: Cpplint fork (https://github.com/cpplint/cpplint)
  cpplint 1.6.1
  Python 3.12.2 (main, Feb  7 2024, 22:13:24) [GCC 13.2.1 20231014]
  editorconfig-checker: 2.7.2
  gitleaks: v8.18.2
  phpstan: PHPStan - PHP Static Analysis Tool 1.10.48
  dotenv-linter: dotenv-linter 3.3.0
  asl-validator: 3.8.2
  actionlint: 1.6.27
  installed by building from source
  built with go1.22.0 compiler for linux/amd64
  tekton-lint: 1.0.0-beta.9
  terrascan: version: v1.18.11
  terraform: 2024/02/28 15:33:48 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
  Terraform v1.7.4
  on linux_amd64
  2024/02/28 15:33:48 traces export: Post "http:///dev/otel-grpc.sock": http: no Host in request URL
  clippy: clippy 0.1.72
  R: R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
  Copyright (C) 2023 The R Foundation for Statistical Computing
  Platform: x86_64-pc-linux-musl (64-bit)
  
  R is free software and comes with ABSOLUTELY NO WARRANTY.
  You are welcome to redistribute it under the terms of the
  GNU General Public License versions 2 or 3.
  For more information about these matters see
  https://www.gnu.org/licenses/.
  rustfmt: rustfmt 1.6.0-stable ( )
  shellcheck: ShellCheck - shell script analysis tool
  version: 0.9.0
  license: GNU General Public License, version 3
  website: https://www.shellcheck.net
  jscpd: 3.5.10
  black: black, 24.2.0 (compiled: no)
  Python (CPython) 3.12.2
  prettier: 3.2.5
  php: PHP 8.2.15 (cli) (built: Jan 18 2024 16:40:05) (NTS)
  Copyright (c) The PHP Group
  Zend Engine v4.2.15, Copyright (c) Zend Technologies
  textlint: v14.0.3
  npm-groovy-lint: GroovyLint: Successfully processed CodeNarc: 
  CodeNarc version 3.3.0
  npm-groovy-lint version 14.2.2
  
  Embeds:
  CodeNarc version 3.3.0
  - Groovy version 3.0.9 (superlite)
  renovate-config-validator: (node:240) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  37.214.0
  golangci-lint: golangci-lint has version 1.56.2 built with go1.22.0 from 58a724a0 on 2024-02-15T20:35:23Z
  kubeconform: v0.6.4
  golangci-lint: golangci-lint has version 1.56.2 built with go1.22.0 from 58a724a0 on 2024-02-15T20:35:23Z
  gherkin-lint: Version command not supported
  eslint: v8.57.0
  scalafmt: scalafmt 3.8.0
  stylelint: 15.11.0
  sqlfluff: sqlfluff, version 2.3.5
  bash-exec: Version command not supported
  google-java-format: google-java-format: Version 1.20.0
  phpcs: PHP_CodeSniffer version 3.8.0 (stable) by Squiz and PHPCSStandards
  terragrunt: terragrunt version v0.55.9
  psalm: Psalm 5.22.1@e9dad66e11274315dac27e08349c628c7d6a1a43
  pylint: pylint 3.1.0
  astroid 3.1.0
  Python 3.12.2 (main, Feb  7 2024, 22:13:24) [GCC 13.2.1 20231014]
  shfmt: v3.8.0
  snakemake: 8.5.3
  arm-ttk: ModuleVersion = 0.24
  pwsh: PowerShell 7.4.1
  mypy: mypy 1.8.0 (compiled: yes)
  eslint: v8.57.0
  coffeelint: 5.2.11
  tflint: TFLint version 0.50.3
  + ruleset.terraform (0.5.0-bundled)
  cfn-lint: cfn-lint 0.85.2
  flake8: 7.0.0 (mccabe: 0.7.0, pycodestyle: 2.11.1, pyflakes: 3.2.0) CPython 3.12.2 on
  Linux
  spectral: 6.11.0
  clj-kondo: clj-kondo v2024.02.12
  eslint: v8.57.0
  ts-standard: 12.0.2
  eslint: v8.57.0
  protolint: protolint version 0.47.6(80ba08f)
  raku: Welcome to Rakudo™ v2023.11.
  Implementing the Raku® Programming Language v6.d.
  Built on MoarVM version 2023.11.
  prettier: 3.2.5
  hadolint: Haskell Dockerfile Linter 2.12.0
  checkstyle: Checkstyle version: 10.13.0
  clang-format: clang-format version 17.0.5 (https://github.com/llvm/llvm-project.git 98bfdac5ce82d1679f8af9a57501471812ab68d7)
  ktlint: 1.1.1
  yamllint: yamllint 1.35.1
  dart: Dart SDK version: 3.3.0 (stable) (Tue Feb 13 10:25:19 2024 +0000) on "linux_x64"
  isort: 
                   _                 _
                  (_) ___  ___  _ __| |_
                  | |/ _/ / _ \/ '__  _/
                  | |\__ \/\_\/| |  | |_
                  |_|\___/\___/\_/   \_/
  
        isort your imports, so you don't have to.
  
                      VERSION 5.13.2
  dotnet: 8.0.101
  eslint: v8.57.0
  rustfmt: rustfmt 1.6.0-stable ( )
  htmlhint: 1.1.4
  rustfmt: rustfmt 1.6.0-stable ( )
  sql-lint: 1.0.0
  checkov: 3.2.26
  lua: Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
  standard: 17.1.0
  2024-02-29 15:36:59 [INFO]   --------------------------------------------
  2024-02-29 15:36:59 [INFO]   Gathering GitHub information...
  2024-02-29 15:36:59 [INFO]   Successfully validated GITHUB_WORKSPACE: /github/workspace
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_EVENT_PATH: /github/workflow/event.json]
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_SHA: 179958b2acfa2481c84f14d7b37c1c76af14e2fc
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_ORG: ***
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_REPO: ***
  2024-02-29 15:36:59 [INFO]   The default branch for this repository is set to: main
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_TOKEN.
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_REPOSITORY: ***
  2024-02-29 15:36:59 [INFO]   Successfully found GITHUB_RUN_ID 8098584347
  2024-02-29 15:36:59 [INFO]   --------------------------------------------
  2024-02-29 15:36:59 [INFO]   Validating the configuration
  .git
  2024-02-29 15:37:00 [INFO]   The main branch doesn't exist in /github/workspace
  f0f312186c3bde435cb87baa7415b29fbf19d639
  2024-02-29 15:37:00 [INFO]   main doesn't exist, however origin/main exists. Setting DEFAULT_BRANCH to: origin/main
  2024-02-29 15:37:03 [INFO]   Building the list of files and directories to check
  2024-02-29 15:37:05 [INFO]   Command output when building the file list:
  ------
  2024-02-29 15:37:04 [FATAL]   Set VALIDATE_GO to false to avoid false positives due to analyzing Go files in the /github/workspace directory individually instead of considering them in the context of a Go module.
  ------
  2024-02-29 15:37:05 [FATAL]   Error when building the list of files and directories to lint.
```

### Steps To Reproduce

Run with this superlinter.yml

```
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Anything else?

The only change between working and failure has been going from,

uses: super-linter/super-linter@v5 -> uses: super-linter/super-linter@v6
