### ISSUE TITLE
GITHUB_BEFORE_SHA Error on Initial Push

### ISSUE THREAD

**Issue by ncalteen** [super-linter/super-linter#5453]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When running `super-linter/super-linter@v6` and `super-linter/super-linter/slim@v6` on the first commit using the following workflow:

```yaml
steps:
  - name: Checkout
    id: checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Setup Node.js
    id: setup-node
    uses: actions/setup-node@v4
    with:
      node-version-file: .node-version
      cache: npm

  - name: Install Dependencies
    id: install
    run: npm ci

  - name: Lint Codebase
    id: super-linter
    uses: super-linter/super-linter/slim@v6
    env:
      DEFAULT_BRANCH: main
      FILTER_REGEX_EXCLUDE: dist/**/*
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TYPESCRIPT_DEFAULT_STYLE: prettier
      VALIDATE_ALL_CODEBASE: false           # Also tested with true
      VALIDATE_JAVASCRIPT_STANDARD: false
      VALIDATE_JSCPD: false
```

I am seeing the following error in the `Super-Linter initialization` step:

```plain
2024-03-29 15:04:20 [FATAL]   Failed to initialize GITHUB_BEFORE_SHA for a push event. Output: HEAD~1
```

I see that this was mentioned previously [here](https://github.com/super-linter/super-linter/issues/5239), however the solution (setting `fetch-depth: 0` in `actions/checkout`) does not seem to resolve the problem.

### Expected Behavior

Super-Linter should run without error (unless there are linting errors)

### Super-Linter version

v6.3.0

### Relevant log output

| Action Version                          | `VALIDATE_ALL_CODEBASE` | Results                                                                                       |
| --------------------------------------- | ----------------------- | --------------------------------------------------------------------------------------------- |
| `super-linter/super-linter/slim@v6.3.0` | `true`                  | [Log Output](https://github.com/ncalteen/linter-test/actions/runs/8482337223/job/23241391159) |
| `super-linter/super-linter/slim@v6.3.0` | `false`                 | [Log Output](https://github.com/ncalteen/linter-test/actions/runs/8482337225/job/23241390928) |
| `super-linter/super-linter@v6.3.0`      | `true`                  | [Log Output](https://github.com/ncalteen/linter-test/actions/runs/8482337231/job/23241391370) |
| `super-linter/super-linter@v6.3.0`      | `false`                 | [Log Output](https://github.com/ncalteen/linter-test/actions/runs/8482337259/job/23241391335) |

### Steps To Reproduce

1. Fork [`actions/javascript-action`](https://github.com/actions/javascript-action)
2. Wait for initial action runs to complete

### Anything else?

Related https://github.com/actions/javascript-action/issues/391

**Comment by ferrarimarco** [comment]
Hi! I've been able to reproduce this in a test case (see #5534). When that PR is ready, it should fix this issue.

**Comment by ferrarimarco** [comment]
@ncalteen The current `latest` tag should be able to handle this scenario. :)

**Comment by stshishkin** [comment]
I've got a similar problem while merging branches without squash. 
```
  fatal: ambiguous argument 'HEAD~4': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  2024-05-03 09:30:17 [FATAL]   Failed to initialize GITHUB_BEFORE_SHA for a push event. Output: HEAD~4
 ```
 version is updated
```
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run linters
      uses: super-linter/super-linter@v6.4.1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_CHECKOV: false
        VALIDATE_JSCPD: false
        VALIDATE_SHELL_SHFMT: false
```
