### ISSUE TITLE
actionlint.yaml not respected

### ISSUE THREAD

**Issue by ssmall** [super-linter/super-linter#5454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have followed the steps in https://github.com/rhysd/actionlint/blob/main/docs/config.md to configure `actionlint.yaml` at the root of my repo. Its contents are not getting picked up by super-linter.

### Expected Behavior

Super-linter respects `actionlint.yaml` when linting GitHub actions.

### Super-Linter version

```markdown
v6.3.0
```

### Relevant log output

I am receiving a GITHUB_ACTIONS lint error from super-linter on GitHub pull requests: 

```shell
label "REDACTED" is unknown. available labels are "windows-latest", "windows-latest-8-cores", "windows-2022", "windows-2019", "windows-2016", "ubuntu-latest", "ubuntu-latest-4-cores", "ubuntu-latest-8-cores", "ubuntu-latest-16-cores", "ubuntu-22.04", "ubuntu-20.04", "macos-latest", "macos-latest-xl", "macos-latest-xlarge", "macos-latest-large", "macos-14-xl", "macos-14-xlarge", "macos-14-large", "macos-14", "macos-14.0", "macos-13-xl", "macos-13-xlarge", "macos-13-large", "macos-13", "macos-13.0", "macos-12-xl", "macos-12-xlarge", "macos-12-large", "macos-12", "macos-12.0", "macos-11", "macos-11.0", "macos-10.15", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
```

### Steps To Reproduce

1. Create `actionlint.yaml` with the following contents:

```yaml
self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - some-nonstandard-runner-name
```

2. Create a workflow called `.github/workflows/test.yml` with contents like the following:

```yaml
name: test
on:
  pull_request:
    branches:
      - main
jobs:
  hello:
    runs-on: some-nonstandard-runner-name
    steps:
    - run: echo Hello world!
```

3. Run super-linter (as a GitHub Action or manually)

### Anything else?

I have also tried moving `actionlint.yaml` to the `.github` directory but the failure is the same.
