### ISSUE TITLE
`macos-14` runner is unknown error

### ISSUE THREAD

**Issue by jsadeli** [super-linter/super-linter#5536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updating the runner to `macos-14` throws a lint error saying it's an unknown label, even though it's already available and runner runs just fine.

### Expected Behavior

no errors

### Super-Linter version

```markdown
slim v5 (latest)
```

### Relevant log output

```shell
.github/workflows/reuseable_build_ios.yml:50:14: label "macos-14" is unknown. available labels are "windows-latest", "windows-2022", "windows-2019", "windows-2016", "ubuntu-latest", "ubuntu-22.04", "ubuntu-20.04", "ubuntu-18.04", "macos-latest", "macos-latest-xl", "macos-13-xl", "macos-13", "macos-13.0", "macos-12-xl", "macos-12", "macos-12.0", "macos-11", "macos-11.0", "macos-10.15", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
```

### Steps To Reproduce

```yaml
name: Reusable Build IOS

on:
  workflow_call:
    inputs:

jobs:
  buildIOS:
    name: Build IOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ secrets.GH_PAT }}
```

### Anything else?

Reference:
- [GitHub Actions: Introducing the new M1 macOS runner available to open source!](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)
