### ISSUE TITLE
Behavior not supported, please either only include (VALIDATE=true) or exclude (VALIDATE=false) linters, but not both

### ISSUE THREAD

**Issue by alexanderbazhenoff** [super-linter/super-linter#5567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, it's me again :) Pushed a changes in two groovy projects, using the latest image in our GitLab CI. First one is ok ([pastebin](https://pastebin.com/qyV2S3qE)), second is ([pastebin](https://pastebin.com/YfRQHabU)):

```
Behavior not supported, please either only include (VALIDATE=true) or exclude (VALIDATE=false) linters, but not both
```

I'm pretty sure I wasn't duplicate anything. Here is my GitLab CI extend:

```yaml
# Didn't removed yet a workaround of ruff cache bug
.super_linter_clean_up: &super_linter_clean_up |
  sudo rm -rf ${SUPER_LINTER_MYPY_CACHE_FOLDER} ${SUPER_LINTER_LOG_FILE} ${SUPER_LINTER_RUFF_CACHE_FOLDER} || true

.ci_super_linter:
  stage: lint
  before_script:
    - *super_linter_clean_up
    - docker pull ${SUPER_LINTER_DOCKER_IMAGE}
  script:
    - docker run -e RUN_LOCAL=true
        -e LINTER_RULES_PATH=${SUPER_LINTER_RULES_PATH}
        -e ACTIONS_RUNNER_DEBUG=${SUPER_LINTER_ACTIONS_RUNNER_DEBUG}
        -e LOG_FILE=${SUPER_LINTER_LOG_FILE}
        -e USE_FIND_ALGORITHM=${SUPER_LINTER_USE_FIND_ALGORITHM}
        -e VALIDATE_PYTHON_MYPY=${SUPER_LINTER_VALIDATE_PYTHON_MYPY}
        -e CREATE_LOG_FILE=${SUPER_LINTER_CREATE_LOG_FILE}
        -e VALIDATE_JSCPD=${SUPER_LINTER_VALIDATE_JSCPD}
        -v ${CI_PROJECT_DIR}:/tmp/lint ${SUPER_LINTER_DOCKER_IMAGE}
  variables:
    SUPER_LINTER_DOCKER_IMAGE: 'ghcr.io/super-linter/super-linter:latest'
    SUPER_LINTER_RULES_PATH: .linters
    SUPER_LINTER_MYPY_CACHE_FOLDER: .mypy_cache
    SUPER_LINTER_RUFF_CACHE_FOLDER: .ruff_cache
    SUPER_LINTER_ACTIONS_RUNNER_DEBUG: 'false'
    SUPER_LINTER_CREATE_LOG_FILE: 'true'
    SUPER_LINTER_LOG_FILE: super-linter.log
    SUPER_LINTER_USE_FIND_ALGORITHM: 'true'
    SUPER_LINTER_VALIDATE_PYTHON_MYPY: 'false'
    SUPER_LINTER_VALIDATE_JSCPD: 'true'
```
Also [.groovylintrc.json](https://pastebin.com/U4mbqHT9), [.yaml-lint.yml](https://pastebin.com/ihJin4dC) and an empty .gitleaks.toml (only comments inside).

Looks like this is a [v6.4.1](https://github.com/super-linter/super-linter/pkgs/container/super-linter) (iamge pull `ghcr.io/super-linter/super-linter:latest`).

Really curious what's wrong?

![super-linter-latest-bug](https://github.com/super-linter/super-linter/assets/19375799/6ca25ce6-2c41-4f92-b8c4-a9ea8f56e669)

I ran it once again in DEBUG mode ([pastebin](https://pastebin.com/5Vif64sg)):

still no attempts to lint a only groovy file in `src/org.company` folder. I have switched to v6.4.0 and the error was the same but colored (BTW, why it's colored?):

![super-linter-6 4 0](https://github.com/super-linter/super-linter/assets/19375799/d0a34ef5-6b90-4cfe-a162-21ac47469863)

Also v6.3.1, v6.3.0, v6.2.0, v6.1.1, v6.1.0, v6.0.0...

I also removed my `.gitleaks.toml`:
```
# See example: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
#[allowlist]
#paths = [
#    '''some_file.sh''',
#]
```
and continue searching for lower version. v5.7.2 is also failed.

Then I mentioned that `VALIDATE_JSCPD=false` in my first project (which is ok). So I turned off them and switched to the latest super-linter, **it's pass**!

![super-linter-no-jscpd-ok](https://github.com/super-linter/super-linter/assets/19375799/b039db46-8a63-4415-8963-bc32e59babb3)

Any ideas about JSCPD?

### Expected Behavior

Expected to start npm-groovy-lint at least, but looks like it's failed on JSCPD.

### Super-Linter version

```markdown
v6.4.1, v6.4.0, v6.3.1
```

### Relevant log output

Pastebin links are in 'Current Behavior' section.

### Steps To Reproduce

The main problem this project can't be a public. But I have [a project](https://github.com/alexanderbazhenoff/jenkins-shared-library) with the same language and project structure.

### Anything else?

Don't know `¯\_(ツ)_/¯`
