### ISSUE TITLE
v6 failing for missing default branch

### ISSUE THREAD

**Issue by cjkrolak** [super-linter/super-linter#5576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in v6.4.1 I see an error that default branch master is missing, I do not see this same failure in v5.0.0.  I'm running as github action.

### Expected Behavior

master branch exists in my repo so this error should not occur

### Super-Linter version

```markdown
v6.4.1
```

### Relevant log output

```shell
2024-04-29 10:43:58 [INFO]   The master branch doesn't exist in /github/workspace
2024-04-29 10:43:58 [INFO]   The origin/master branch doesn't exist in /github/workspace
2024-04-29 10:43:58 [FATAL]   Neither master, nor origin/master exist in /github/workspace
```

### Steps To Reproduce

upgrade superlinter to version 6.4.1 and run

### Anything else?

no

**Comment by ferrarimarco** [comment]
Hi! There aren't enough data points to understand what's happening here. Can you post your super-linter configuration?

**Comment by cjkrolak** [comment]
```
name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_INCLUDE: .*src/.*  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ferrarimarco** [comment]
Closing for the lack of replies. We can reopen if anything comes up.

**Comment by jasonkarns** [comment]
I'm getting the same error:

Failed run: https://github.com/nodenv/actions/actions/runs/9245118639/job/25431170647?pr=64

```yml
jobs:
  test-lint:
    uses: nodenv/.github/.github/workflows/test.yml@v3
```

referenced workflow:

```yml
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write # to report status checks
    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - uses: super-linter/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
```
