### ISSUE TITLE
Update Golang linter configuration to avoid the deprecated `linters.govet.check-shadowing` option

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [super-linter/super-linter#5605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
level=warning msg="[config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`."
level=error msg="[linters_context] typechecking error: named files must all be in one directory; have /github/workspace/response and /github/workspace/responsetranslator"
```

we haven't applied any linter configuration settings. we're wondering about that warning.
how we use it in our workflow:
```
      - name: Super Linter Code Base
        uses: github/super-linter/slim@v6
        env:
          FILTER_REGEX_EXCLUDE: "**/*_test.go"
          DEFAULT_BRANCH: master
          VALIDATE_GO_MODULES: true
          VALIDATE_BASH: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Thanks

### Expected Behavior

no warning to appear.

### Super-Linter version

```markdown
slim image v6.4.1
```

### Relevant log output

```shell
see description.

https://github.com/centralnicgroup-opensource/rtldev-middleware-go-sdk/actions/runs/8939075947/job/24558831196?pr=136
```

### Steps To Reproduce

1) you may fork our go-sdk repo
2) we have a shareable workflow in place, related superlinter action plugin usage snippet  provided. go version installed v1.22.2
3) no linter config file in place for golang, so falling back to super-linter's defaults
