### ISSUE TITLE
Accept an option to dump log output to github Job Summaries

### ISSUE THREAD

**Issue by jasonkarns** [super-linter/super-linter#5650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current log output is not the greatest for digging into violations on github actions.

### Expected Behavior

Now that github actions has [Job Summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), it would be awesome if super-linter's log output could be redirected directly to the job summary. That way the linter output could be easily consumable from the job page instead of diving into the logs.

**Comment by jasonkarns** [comment]
In the (present) absence of an official feature, is there any existing way to redirect the log output to the job summaries file descriptor now?

I've tried:

```yml
      - uses: github/super-linter/slim@v6
        env:
          # /snip
          CREATE_LOG_FILE: true
          LOG_FILE: ${{ github.step_summary }}
```

but that fails:

```
mv: cannot move '/tmp/tmp.zGd3tC9yAF' to '/github/workspace//github/file_commands/step_summary_a2525f8f-5bd7-40c1-9437-d3d36f44bdf2': No such file or directory
```
