### ISSUE TITLE
logfile permissions are denied to subsequent steps

### ISSUE THREAD

**Issue by jasonkarns** [super-linter/super-linter#5658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to redirect the log file output to GitHub Job Summaries.

```
      - uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_LOG_FILE: true
          # /snip
      - if: always()
        run: cat super-linter.log >> $GITHUB_STEP_SUMMARY
```

But catting the logfile gives a permissions error.

### Expected Behavior

I'd expect subsequent steps to have access to the log file that is created.

### Super-Linter version

```markdown
slim-v6.4.1
```

### Relevant log output

```shell
Run cat super-linter.log >> $GITHUB_STEP_SUMMARY
  cat super-linter.log >> $GITHUB_STEP_SUMMARY
  shell: /usr/bin/bash -e {0}
cat: super-linter.log: Permission denied
Error: Process completed with exit code 1.
```

### Steps To Reproduce

on github actions
run while creating log file
attempt to read log file after step is complete
