### ISSUE TITLE
ESLint Fails to Parse Configuration File with .mjs Extension

### ISSUE THREAD

**Issue by DorianKr** [super-linter/super-linter#5678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am encountering an issue with ESLint where it fails to parse configuration files that have a .mjs extension. When using `eslint.config.mjs` file for the ESLint configuration, ESLint throws a YAMLException error, indicating it is incorrectly attempting to parse the file as YAML: 
```js
YAMLException: Cannot read config file: /path/to/eslint.config.mjs
Error: end of the stream or a document separator is expected (9:12)
    6 |
    7 | export default [
    8 |   {
    9 |     ignores: ['dist']
-----------------^
   10 |   },
   11 |   {
```

In contrast, using a configuration file with a .js or .cjs file works correctly without any errors.

### Expected Behavior

ESLint should correctly parse and apply configuration files with a .mjs extension as JavaScript files, similar to .js and .cjs extensions.

### Super-Linter version

```markdown
v6.4.1
```

### Relevant log output

```shell
2024-05-23 20:03:51 [INFO]   Linting TSX items...
  Error: -23 20:03:52 [ERROR]   Found errors when linting TSX. Exit code: 1.
  2024-05-23 20:03:52 [INFO]   Stderr contents for TSX:
  ------
  
  Oops! Something went wrong! :(
  
  ESLint: 8.57.0
  
  YAMLException: Cannot read config file: /github/workspace/client/eslint.config.mjs
  Error: end of the stream or a document separator is expected (15:12)
  
   12 | 
   13 | export default [
   14 |   {
   15 |     ignores: ['dist']
  -----------------^
   16 |   },
   17 |   {
      at generateError (/node_modules/js-yaml/lib/loader.js:183:10)
      at throwError (/node_modules/js-yaml/lib/loader.js:187:9)
      at readDocument (/node_modules/js-yaml/lib/loader.js:1645:5)
      at loadDocuments (/node_modules/js-yaml/lib/loader.js:1688:5)
      at Object.load (/node_modules/js-yaml/lib/loader.js:1714:19)
      at loadLegacyConfigFile (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2565:21)
      at loadConfigFile (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2680:20)
      at ConfigArrayFactory._loadConfigData (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2984:42)
      at ConfigArrayFactory.loadFile (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2850:40)
      at createCLIConfigArray (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3660:35)
  ------
```

### Steps To Reproduce

  1. Create an ESLint configuration file with the .mjs extension, e.g., `eslint.config.mjs`.
  2.  Run ESLint and observe the YAMLException error.

### Anything else?

Maybe my configurations are wrong. This is my first time doing this.

### eslint.config.mjs

```js
import globals from 'globals'
import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import eslintJsPlugin from '@eslint/js'
import stylisticJsx from '@stylistic/eslint-plugin-jsx'

export default [
  {
    ignores: ['dist']
  },
  {
    rules: eslintJsPlugin.configs.recommended.rules
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: { modules: true, jsx: true },
        ecmaVersion: 'latest',
        project: 'tsconfig.json'
      },
      globals: {
        ...globals.node,
        ...globals.browser
      }
    },
    plugins: {
      '@stylistic/jsx': stylisticJsx,
      '@typescript-eslint': tsPlugin,
      tsPlugin
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      '@stylistic/jsx/jsx-indent': ['error', 2],
      'no-undef': 'off'
    }
  }
]
```

### super-linter.yml
```yml
---
name: Lint Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: { }
jobs:
  run-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /client
          TYPESCRIPT_ES_CONFIG_FILE: eslint.config.mjs
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: ${DEFAULT_WORKSPACE}/client/tsconfig.json
```
