### ISSUE TITLE
TERRAFORM_TERRASCAN_CONFIG_FILE doesn't work

### ISSUE THREAD

**Issue by yuritur** [super-linter/super-linter#5762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

If you set TERRAFORM_TERRASCAN_CONFIG_FILE to some **/*.toml path, it doesn't work.

### Expected Behavior

It should work without issues and take rules from TERRAFORM_TERRASCAN_CONFIG_FILE.

### Super-Linter version

```markdown
v6.6.0
```

### Relevant log output

```shell
  2024-06-11 21:22:54 [FATAL]     -> TERRAFORM_TERRASCAN_LINTER_RULES rules file (/action/lib/.automation/infra/terrascan.toml) doesn't exist.
```

### Steps To Reproduce

1. Set TERRAFORM_TERRASCAN_CONFIG_FILE to some unusual terrascan.toml path.
2. Run super linter

### Anything else?

Most likely, you have old or legacy TERRAFORM_TERRASCAN_LINTER_RULES parameter, which should be replaced by TERRAFORM_TERRASCAN_CONFIG_FILE.

https://github.com/super-linter/super-linter/blob/5b5d2f7ef0c308f904d2e30528e6dddad0a3498a/lib/functions/linterCommands.sh#L127

**Comment by ferrarimarco** [comment]
Hi!

Can you post your super-linter configuration?

> ### Anything else?
> Most likely, you have old or legacy TERRAFORM_TERRASCAN_LINTER_RULES parameter, which should be replaced by TERRAFORM_TERRASCAN_CONFIG_FILE.
> 
> https://github.com/super-linter/super-linter/blob/5b5d2f7ef0c308f904d2e30528e6dddad0a3498a/lib/functions/linterCommands.sh#L127

I don't think so. The `TERRAFORM_TERRASCAN_LINTER_RULES` is automatically created by Super-linter. Its value is the full path to the terrascan configuration file.

**Comment by yuritur** [comment]
@ferrarimarco
```
      - name: Run Lint
        uses: super-linter/super-linter/slim@v6.6.0
        env:
          # enforce linting of all files
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.SUPER_LINTER_GH_TOKEN }}

          # Remove Python linting, because we use more specific rules in another GitHub Actions workflow.
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_ISORT: false

          TERRAFORM_TERRASCAN_CONFIG_FILE: "infra/terrascan.toml"
```
I added parameter as explained [here](https://github.com/super-linter/super-linter#:~:text=TERRAFORM_TERRASCAN_CONFIG_FILE).

Maybe I missed something, but I see that this parameter is only used here:
https://github.com/super-linter/super-linter/blob/5b5d2f7ef0c308f904d2e30528e6dddad0a3498a/lib/linter.sh#L245

And TERRAFORM_TERRASCAN_FILE_NAME is never used in any other part of the code.
