### ISSUE TITLE
YamlLint does not use "local" config file

### ISSUE THREAD

**Issue by neilime** [super-linter/super-linter#5791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Hi,

Yamllint is not using "local"  `.yaml-lint.yml`. 

When there is a configuration located in  `.github/linters/.yaml-lint.yml`, [YamlLint](https://github.com/adrienverge/yamllint) does not use it

### Expected Behavior

When there is a configuration located in  `.github/linters/.yaml-lint.yml`, [YamlLint](https://github.com/adrienverge/yamllint) should use it

### Super-Linter version

```markdown
v6.6.0
```

### Relevant log output

```shell
N/A
```

## First case:

Create a config file `.github/linters/.yaml-lint.yml`  - Deliberately erroneous

```yml
extends: default

wrong
```

Run the CI, you should have an error like invalid config: mapping values are not allowed here, but you will not as it does not use the config file

```yml
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Second case: force absolute path of config file

```yml
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

You will have the following error: `YAML_LINTER_RULES rules file (/action/lib/.automation//github/workspace/.github/linters/.yaml-lint.yml) doesn't exist.`

## Workaround:

Set relative path (from `/action/lib/.automation`)

```yml
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE: "../../../github/workspace/.github/linters/.yaml-lint.yml"
```
