### ISSUE TITLE
Ability to specify a specific version of a given linter

### ISSUE THREAD

**Issue by mikelax** [super-linter/super-linter#5923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently each version of super-linter includes a specific set of library versions and included linter versions. This leads to predictable behavior for a given version of super-linter, it slows does the ability to use newer linters when new features or bugfixes are released. 

### Expected Behavior

It would be nice if there was the ability to specify a linter version as an attribute to the workflow. 
The attributes could share a common prefix, such as `VERSION_`

example: 

```yaml
  - name: Lint code
    uses: super-linter/super-linter/slim@v6
      env:
        VALIDATE_CHECKOV: true
        VERSION_CHECKOV: 3.2.199
```
