### ISSUE TITLE
Regression of pylint config - import-error's are no longer disabled

### ISSUE THREAD

**Issue by Shop-kins** [super-linter/super-linter#5926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

When using the latest version of super linter import errors are not ignored!

This means i will have to update each repos config to ignore import errors despite previously having no expectation for import errors to succeed while using super-linter

This seems to have been changed as of: https://github.com/super-linter/super-linter/pull/5252

### Expected Behavior

Import errors arnt reported by pylint inside of the super-linter i.e. the following error shouldnt show up:

E0401: Unable to import '***' (import-error)

### Super-Linter version

```markdown
super-linter/super-linter/slim@3fe03abab2eafb293ace16d4a3b07aeabcb3f1a0

(v6.7.0)
```

### Super-linter configuration

```yaml
- name: checkout code
  uses: actions/checkout@a5ac7e51....
  with:
    fetch-depth: 0
- name: Lint
  uses: super-linter/super-linter/slim@3fe03abab2eafb293ace16d4a3b07aeabcb3f1a0
  env:
    DEFAULT_BRANCH: main
    GITHUB_TOKEN: {token}
    #disable non pylint things e.g. VALIDATE_PYTHON_MYPY: false
    LINTER_RULES_PATH: .github/linters #fails without this aswell
```

### Relevant log output

```shell
E0401: Unable to import '***' (import-error)
```

### Steps To Reproduce

Create a python file with 3rd party library imports (e.g. terrasnek)

Run the super linter using github actions!

I am having trouble running the docker file myself to create a simple step by step guide to reproduce this (being on arm64 probably doesnt help) however you can almost certainly follow the steps from previous issue: https://github.com/super-linter/super-linter/issues/3180 but with update docker commands
