### ISSUE TITLE
Prettier and standardjs are incompatible

### ISSUE THREAD

**Issue by dunglas** [super-linter/super-linter#5954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Both prettier and standardjs are executed by default, but their rules seem incompatible.
Running standardjs to format JS files makes prettier red and vice versa.

Made than only one should be executed, or that custom configuration should be created to make the compatible.

### Expected Behavior

Having a way to get all linters green without relying on a custom configuration file.

### Super-Linter version

```markdown
v6.8.0
```

### Super-linter configuration

```yaml
---
name: Lint Code Base
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
  packages: read
  statuses: write  
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Lint Code Base
        uses: super-linter/super-linter/slim@v6.8.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdown-lint.yaml
          VALIDATE_CPP: false
          VALIDATE_JSCPD: false
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PHPSTAN: false
          VALIDATE_PHP_PSALM: false
          VALIDATE_TERRAGRUNT: false
          # Prettier and StandardJS are incompatible
          #VALIDATE_JAVASCRIPT_PRETTIER: false
          #VALIDATE_TYPESCRIPT_PRETTIER: false
```

### Relevant log output

```shell
Error: -03 09:05:23 [ERROR]   Errors found in JAVASCRIPT_PRETTIER
Notice: 03 09:05:23 [NOTICE]   Successfully linted JAVASCRIPT_STANDARD
```

### Steps To Reproduce

Run the latest version of super-linter on https://github.com/dunglas/frankenphp.
