### ISSUE TITLE
Cannot find rubocop-rspec_rails on v6.8.0

### ISSUE THREAD

**Issue by jandresrodriguez** [super-linter/super-linter#5980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Rubocop can't run, throwing errors

### Expected Behavior

Rubocop should run!

### Super-Linter version

```markdown
v6.8.0
```

### Super-linter configuration

```yaml
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Super-Linter

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: [push]

permissions:
  contents: read
  packages: read
  statuses: write

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Super-Linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    timeout-minutes: 10

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Super-Linter
        uses: super-linter/super-linter@latest
        env:
          DEFAULT_BRANCH: develop
          FILTER_REGEX_EXCLUDE: ./db/schema.rb
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          RUBY_CONFIG_FILE: '.rubocop.yml'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          YAML_CONFIG_FILE: '.yaml-lint.yml'
          YAML_ERROR_ON_WARNING: false
```

### Relevant log output

```shell
RUBY
  2024-08-06 14:55:14 [INFO]   Linting RUBY items...
  Error: -06 14:55:20 [ERROR]   Found errors when linting RUBY. Exit code: 1.
  2024-08-06 14:55:20 [INFO]   Stderr contents for RUBY:
  ------
  cannot load such file -- rubocop-rspec_rails
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/feature_loader.rb:46:in `rescue in rescue in load'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/feature_loader.rb:39:in `rescue in load'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/feature_loader.rb:32:in `load'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/feature_loader.rb:21:in `load'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_loader_resolver.rb:14:in `block (2 levels) in resolve_requires'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
  <internal:kernel>:90:in `tap'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_loader.rb:52:in `load_file'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/config_store.rb:29:in `options_config='
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/cli.rb:156:in `act_on_options'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/cli.rb:47:in `block in run'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/cli.rb:77:in `profile_if_needed'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/lib/rubocop/cli.rb:43:in `run'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/exe/rubocop:19:in `block in <top (required)>'
  /usr/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
  /usr/lib/ruby/gems/3.3.0/gems/rubocop-1.62.1/exe/rubocop:19:in `<top (required)>'
  /usr/bin/rubocop:25:in `load'
  /usr/bin/rubocop:25:in `<main>'
  ------
```

### Steps To Reproduce

I wasn't able to run it locally :(

**Comment by ferrarimarco** [comment]
Hi. There's not enough information to understand what's happening.

How is your Ruby configuration file like? Is the repository public, so we can have a look at its structure?

Especially, the way you configured Super-linter means that it expects a file named `.rubocop.yml` in the root of your repository.

Unless we have that information, there's not much we can do.

**Comment by jandresrodriguez** [comment]
Hey @ferrarimarco , thanks for the quick response !

Leaving the `rubocop.yml` below!

```
AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']

RSpec/ExampleLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/Documentation:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
```
