### ISSUE TITLE
Support adding multiple custom options

### ISSUE THREAD

**Issue by detiber** [super-linter/super-linter#6084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Using a .env file for shared configuration as documented (https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md#share-environment-variables-between-environments) and setting multiple command line arguments for kubeconform requires using an unquoted string, which causes dotenv-linter to flag it as an error.

Quoting the string to resolve the error results in kubeconform to be unable to parse the command line arguments, since they are treated as a singular quoted argument.

Adding a comment to the top of the shared .env configuration, casues the github action to fail, with an invalid format error.

```sh
# dotenv-linter:off ValueWithoutQuotes
KUBERNETES_KUBECONFORM_OPTIONS=-schema-location default -schema-location https://json.schemastore.org/kustomization.json
```
Which required me to update loading the shared config to use `| grep -v '^#` before appending to "$GITHUB_ENV"

### Expected Behavior

To be able to leverage shared configuration, configure kubeconform to properly support the schema needed for linting kustomize configuration, and keep dotenv linting enabled without needing to worry about hacky workarounds and error prone config.

### Super-Linter version

```markdown
v7.0.0
```

### Super-linter configuration

```yaml
# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
---
name: lint

on:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request:

# Declare default permissions as read-only
permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: 🔒 harden runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Load super-linter configuration
        # The grep is needd here because:
        # - github actions will not accept comments here
        # - kubeconform does not support config file or env variable configuration settings, only commandd line arguments
        # - kubeconform needs a schema configured to support kustomize files
        # - super-linter only supports configuring kubeconform command line arguments through the KUBERNETES_KUBECONFORM_OPTIONS env var
        # - super-linter requires KUBERNETES_KUBECONFORM_OPTIONS to be unquoted for kubeconform to process the arguments properly
        # - dotenv-linter doesn't support fine grained config outside of using comments to disable checks selectively
        # - super-linter doesn't expose a way to provide command line options to dotenv-linter
        run: cat .github/super-linter.env .github/super-linter-default-validate.env  | grep -v '^#' >> "$GITHUB_ENV"
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Relevant log output

```shell
Error without using `grep -v`:


Run cat .github/super-linter.env .github/super-linter-default-validate.env >> "$GITHUB_ENV"
  cat .github/super-linter.env .github/super-linter-default-validate.env >> "$GITHUB_ENV"
  shell: /usr/bin/bash -e {0}
Error: Unable to process file command 'env' successfully.
Error: Invalid format '# dotenv-linter:off ValueWithoutQuotes'
```

### Steps To Reproduce

Using the following .env file with the github actions workflow above:

```sh
KUBERNETES_KUBECONFORM_OPTIONS=-schema-location default -schema-location https://json.schemastore.org/kustomization.json
```

Error with quoted KUBERNETES_KUBECONFORM_OPTIONS:

```sh
KUBERNETES_KUBECONFORM
  2024-08-22 19:51:59 [INFO]   Linting KUBERNETES_KUBECONFORM items...
  Error: -22 19:51:59 [ERROR]   Found errors when linting KUBERNETES_KUBECONFORM. Exit code: 1.
  2024-08-22 19:51:59 [INFO]   Stderr contents for KUBERNETES_KUBECONFORM:
  ------
  flag provided but not defined: -schema-location default -schema-location https://json.schemastore.org/kustomization.json
  Usage: kubeconform [OPTION]... [FILE OR FOLDER]...
    -cache string
      	cache schemas downloaded via HTTP to this folder
    -debug
      	print debug information
    -exit-on-error
      	immediately stop execution when the first error is encountered
    -h	show help information
    -ignore-filename-pattern value
      	regular expression specifying paths to ignore (can be specified multiple times)
    -ignore-missing-schemas
      	skip files with missing schemas instead of failing
    -insecure-skip-tls-verify
      	disable verification of the server's SSL certificate. This will make your HTTPS connections insecure
    -kubernetes-version value
      	version of Kubernetes to validate against, e.g.: 1.18.0 (default master)
    -n int
      	number of goroutines to run concurrently (default 4)
    -output string
      	output format - json, junit, pretty, tap, text (default "text")
    -reject string
      	comma-separated list of kinds or GVKs to reject
    -schema-location value
      	override schemas location search path (can be specified multiple times)
    -skip string
      	comma-separated list of kinds or GVKs to ignore
    -strict
      	disallow additional properties not in schema or duplicated keys
    -summary
      	print a summary at the end (ignored for junit output)
    -v	show version information
    -verbose
      	print results for all resources (ignored for tap and junit output)
  ------
```

Error with unquoted KUBERNETES_KUBECONFORM_CONFIG, but without the dotenv-linter comment:

```
------
Checking .github/super-linter-default-validate.env
Checking .github/super-linter.env
.github/super-linter.env:2 ValueWithoutQuotes: This value needs to be surrounded in quotes

Checking scripts/super-linter-local.env

Found 1 problem
------
```

### Anything else?

There are multiple ways to address this since it's the interaction of multiple different projects, how they can be configured, how super-linter exposes config for the linters involved, etc.

A quick fix may be to improve the way that multiple command line arguments can be passed to kubeconform, but even that isn't without awkward edge cases that wouldd need to be resolved.

Longer term, it would be good to try and coordinate improvements between the tools and how super-linter interacts with them to avoid needing to hack workarounds in user implementations or within super-linter itself.

**Comment by ferrarimarco** [comment]
You have a point here, although I would classify this as an enhancement request.

The main problem is that some tools expose some configuration variables only using command line options, and not a configuration file, so it become necessary to provide a way to set these options.

Parsing commands using an `.env` file is somewhat fragile, as you reported, so we need a better way of handling this.

**Comment by ferrarimarco** [comment]
By the way, this is one of the reasons why we switched to Bash arrays to dynamically compose commands. So maybe the solution is to provide something along those lines.

**Comment by detiber** [comment]
> You have a point here, although I would classify this as an enhancement request.
> 
> The main problem is that some tools expose some configuration variables only using command line options, and not a configuration file, so it become necessary to provide a way to set these options.
> 
> Parsing commands using an `.env` file is somewhat fragile, as you reported, so we need a better way of handling this.

@ferrarimarco I was on the fence about whether to file as a bug or an enhancement, I went with bug since it is likely to impact other users as well.

It might be good to document a "supported" workaround in the docs until proper support can be implemented.

**Comment by ferrarimarco** [comment]
Makes sense. Let's see what we'd need to do first, then we can think if it's better to first document a workaround.

And thanks for providing some examples. Those are going to be useful as test cases.

Currently, Super-linter supports the following configuration variables to dynamically pass command arguments:

- `BASH_SEVERITY`: supporting this in a Shellcheck configuration file is tracked by https://github.com/koalaman/shellcheck/issues/2178
- `GITHUB_ACTIONS_COMMAND_ARGS`: the configuration file supports a small subset of options.
- `KUBERNETES_KUBECONFORM_OPTIONS`: no config file support, so we need this to pass variables.
- `MARKDOWN_CUSTOM_RULE_GLOBS`: used to pass to markdownlint `-r, --rules <file|directory|glob|package>  include custom rule files (default: [])` ([ref](https://github.com/igorshubovych/markdownlint-cli))

**Comment by ferrarimarco** [comment]
`BASH_SEVERITY` and `MARKDOWN_CUSTOM_RULE_GLOBS` might work as they are, while `GITHUB_ACTIONS_COMMAND_ARGS` and `KUBERNETES_KUBECONFORM_OPTIONS` are likely impacted by this issue.

**Comment by ferrarimarco** [comment]
After checking a bit, I think this is actually a bug because we need additional processing after loading the environment variable where the options are stored. Adding it as it is to the array that we use to run commands is not going to work.

**Comment by detiber** [comment]
> By the way, this is one of the reasons why we switched to Bash arrays to dynamically compose commands. So maybe the solution is to provide something along those lines.

I tried to avoid suggesting any particular fix or direction when filing the issue, since any solution that would avoid me having to document, maintain, and support fragile workarounds when using super-linter is the main requirement.

That said, ideally, I would love to be able to leverage some type of schema-backed, structured config file format for configuring super-linter, and to be able to pass those config files using both command line arguments and github actions arguments:

```sh
docker run -v "${PWD}":/tmp/lint --platform linux/amd64 ghcr.io/super-linter/super-linter:latest --config=/tmp/lint/config1.<extension> --config=config2.<extension>
```

instead of:

```sh
docker run --env-file ".github/super-linter.env" --env-file ".github/super-linter-default-validate.env" --env-file "scripts/super-linter-local.env" -v "${PWD}":/tmp/lint --platform linux/amd64 ghcr.io/super-linter/super-linter:latest
```

and:

```yaml
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config:
            - config1.<extension>
            - config2.<extension>          
```

instead of:

```yaml
      - name: Load super-linter configuration
        run: cat .github/super-linter.env .github/super-linter-default-validate.env  | grep -v '^#' >> "$GITHUB_ENV"
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
