### ISSUE TITLE
Schema-based configuration file

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#6086]
(Moving this request to its own issue.)

I tried to avoid suggesting any particular fix or direction when filing the issue, since any solution that would avoid me having to document, maintain, and support fragile workarounds when using super-linter is the main requirement.

That said, ideally, I would love to be able to leverage some type of schema-backed, structured config file format for configuring super-linter, and to be able to pass those config files using both command line arguments and github actions arguments:

```sh
docker run -v "${PWD}":/tmp/lint --platform linux/amd64 ghcr.io/super-linter/super-linter:latest --config=/tmp/lint/config1.<extension> --config=config2.<extension>
```

instead of:

```sh
docker run --env-file ".github/super-linter.env" --env-file ".github/super-linter-default-validate.env" --env-file "scripts/super-linter-local.env" -v "${PWD}":/tmp/lint --platform linux/amd64 ghcr.io/super-linter/super-linter:latest
```

and:

```yaml
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config:
            - config1.<extension>
            - config2.<extension>          
```

instead of:

```yaml
      - name: Load super-linter configuration
        run: cat .github/super-linter.env .github/super-linter-default-validate.env  | grep -v '^#' >> "$GITHUB_ENV"
      - name: 🧹 run superlinter
        uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b # v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

_Originally posted by @detiber in https://github.com/super-linter/super-linter/issues/6084#issuecomment-2313516258_
