### ISSUE TITLE
Super Linter will not lint .tsx files

### ISSUE THREAD

**Issue by mccabe-david** [super-linter/super-linter#6115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [ ] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

All my .ts files are linted, but my .tsx files are not found by the linter

### Expected Behavior

Both types of files should be linted

### Super-Linter version

```markdown
v6.7.0
```

### Super-linter configuration

```yaml
---
name: Lint

on:  # yamllint disable-line rule:truthy
  push: null

permissions: { }

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.7.0  # x-release-please-version
        env:
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: "tsconfig.json"
          VALIDATE_BASH: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_GROOVY: false
          VALIDATE_JAVA: false
          VALIDATE_SHELL_SHFMT: false
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
tsconfig.json:
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "compilerOptions": {
    "target": "ES2022",
    "jsx": "react",
    "module": "ES2022", 
    "moduleResolution": "node",
    "skipLibCheck": true,       
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true
  },
  "include": ["src/**/*.tsx", "src/**/*.ts", "*.ts", "*.tsx", "/tmp/lint/test/linters"],
  "exclude": ["node_modules/"]
}
```

### Relevant log output

```shell
/github/workspace/app.d.ts:1:1: Do not use a triple slash reference for nativewind/types, use `import` style instead. (@typescript-eslint/triple-slash-reference)
    /github/workspace/app.d.ts:2:1: Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)
 ...
```

### Steps To Reproduce

1. Create a repo with .ts and .tsx files in the root directory
2. Set up and run Super Linter 

### Anything else?

<img width="236" alt="Screenshot 2024-09-04 at 4 56 38 PM" src="https://github.com/user-attachments/assets/de53ab15-e9d7-402f-9bba-f8cb4b4e4001">
My .tsx file in the same directory as a .ts file being scanned

[This](https://www.npmjs.com/package/@tsconfig/react-native) is the page with the RN tsconfig.json file
