### ISSUE TITLE
JSCPD linting TSX files as Javascript

### ISSUE THREAD

**Issue by mccabe-david** [super-linter/super-linter#6140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

<img width="867" alt="Screenshot 2024-09-11 at 3 52 25 PM" src="https://github.com/user-attachments/assets/cfce96fb-d26f-4244-b213-c4c54bd8c12b">
There are incorrect clone hits on my .tsx files
<img width="822" alt="Screenshot 2024-09-11 at 3 54 54 PM" src="https://github.com/user-attachments/assets/15c2a4ed-6ca2-4d1f-ac8f-f23006bd5ebc">

### Expected Behavior

JSCPD should not lint these files as Javascript

### Super-Linter version

```markdown
v6.7.0
```

### Super-linter configuration

```yaml
---
name: Lint

on:  # yamllint disable-line rule:truthy
  push: null

permissions: { }

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.7.0  # x-release-please-version
        env:
          TYPESCRIPT_ES_CONFIG_FILE: .myeslintrc.yml
          VALIDATE_BASH: false
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_GROOVY: false
          VALIDATE_JAVA: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_SHELL_SHFMT: false
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
```

### Relevant log output

```shell
Clone found (javascript):
   - /github/workspace/src/screens/SuccessfulOrder.tsx [77:2 - 88:16] (11 lines, 186 tokens)
     /github/workspace/src/screens/SuccessfulOrder.tsx [69:2 - 82:15]
  
   77 │ 69 │ }>                                                                                                                                                                                
   78 │ 70 │                 <StyledText className='text-2xl font-bold mt-[2.5%]'>{'Confirming your order...'}</StyledText>                                                                    
   79 │ 71 │                 <StyledText className='text-xl text-slate-400 mb-[5%]'>{order.merchantName}</StyledText>                                                                          
   80 │ 72 │               </Container>                                                                                                                                                        
   81 │ 73 │     case 'Preparing':                                                                                                                                                             
   82 │ 74 │       return  <Container style={{borderBottomWidth: 2, borderBottomColor: 'gray',borderTopWidth: 2, borderTopColor: 'gray', width: '95%', justifyContent: 'center', padding: 5}}> 
   83 │ 75 │                 <StyledText className='text-2xl font-bold mt-[2.5%]'>{'Preparing your order...'}</StyledText>                                                                     
   84 │ 76 │                 <StyledText className='text-xl text-slate-400'>{order.merchantName}</StyledText>                                                                                  
   85 │ 77 │                 <StyledText className='text-xl text-slate-400 mb-[5%]'>{'Pickup: ' + pickupTime}</StyledText>                                                                     
   86 │ 78 │               </Container>                                                                                                                                                        
   87 │ 79 │     case 'Ready':                                                                                                                                                                 
   88 │ 80 │       return  <Container style={{borderBottomWidth: 2, borderBottomColor: 'gray', borderTopWidth
```

### Steps To Reproduce

1. Add a .tsx file to a new react-native project
2. Write some functions with switch statements that return jsx elements

### Anything else?

The weirdest thing is that the ranges for lines where these "duplicates" are not even the same size. Apparently, there are 82 lines of code between line 82 and line 94...
