### ISSUE TITLE
`commitlint` behavior issues

### ISSUE THREAD

**Issue by claudioandre-br** [super-linter/super-linter#6316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

The Docker "slim" image of super-linter includes `commitlint` [1], as expected. So, this works:

```
docker run --rm -e RUN_LOCAL=true -e DEFAULT_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  -e ENFORCE_COMMITLINT_CONFIGURATION_CHECK=true \
  -e VALIDATE_GIT_COMMITLINT=true \
  -v $(pwd):/tmp/lint ghcr.io/super-linter/super-linter:slim-latest
```

But the standard image does not. So the below fails silently:
```
docker run --rm -e RUN_LOCAL=true -e DEFAULT_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  -e ENFORCE_COMMITLINT_CONFIGURATION_CHECK=true \
  -e VALIDATE_GIT_COMMITLINT=true \
  -v $(pwd):/tmp/lint ghcr.io/super-linter/super-linter:v7.1.0
```
GIT_COMMITLINT is not executed for the command above. No errors, no hints, nothing.

This also works (this looks "slim", e.g., no `goreleaser` banner):
```
docker run --rm -e RUN_LOCAL=true -e DEFAULT_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  -e ENFORCE_COMMITLINT_CONFIGURATION_CHECK=true \
  -e VALIDATE_GIT_COMMITLINT=true \
  -v $(pwd):/tmp/lint ghcr.io/super-linter/super-linter:latest
```

[1] [GIT_COMMITLINT] commitlint: @commitlint/cli@19.5.0

### Expected Behavior

`standard`: `super-linter/super-linter@[VERSION]`: includes all supported linters.

All means ALL.

### Super-Linter version

```markdown
v7.1.0
```

### Super-linter configuration

```yaml
- name: Linter
        uses: super-linter/super-linter@b92721f792f381cedc002ecdbb9847a15ece5bb8 # v7.1.0
        env:
          ENABLE_COMMITLINT_STRICT_MODE: true
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CHECKOV: false
          VALIDATE_GIT_COMMITLINT: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Relevant log output

```shell
There is no error. Nothing to add here.
```

### Steps To Reproduce

Run this command and try to find any reference of `commitlint`.
```
docker run --rm -e RUN_LOCAL=true -e DEFAULT_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
  -e ENFORCE_COMMITLINT_CONFIGURATION_CHECK=true \
  -e VALIDATE_GIT_COMMITLINT=true \
  -v $(pwd):/tmp/lint ghcr.io/super-linter/super-linter:v7.1.0
```

### Anything else?

BTW: 
* commitlint does not obey the  `LINTER_RULES_PATH` variable. This is confusing and undocumented.
* Version [7.1.0](https://github.com/super-linter/super-linter/compare/v7.0.0...v7.1.0) (2024-08-27) is tagged as “latest”, but is not related to the “latest” Docker image. 
  * Should the Docker image be `devel` or `testing`?

**Comment by ferrarimarco** [comment]
Hi!

This is expected because we 7.1.0 doesn't include commitlint, and we didn't release 7.2.0 yet.

But you have a point about documentation. It might be helpful to mention that.

**Comment by claudioandre-br** [comment]
Probably a better solution: you guys should run `commitlint` with the `-g "$LINTER_RULES_PATH"` option.

```
-g, --config         path to the config file; result code 9 if config is missing
```

**Comment by claudioandre-br** [comment]
PS: I found it uncertain whether I needed to report a new issue or not. Is it documentaion too? A different bug?

More information about commitlint behavior:
- Commitlint is unable to detect when a PR has more than one commit> For example:
  - https://github.com/claudioandre-br/john-packages/actions/runs/12107930810

I was expecting a `--from ...` commitlint command line. But instead:

`PARALLEL_COMMAND for GIT_COMMITLINT after LINTER_COMMAND_ARRAY concatenation: parallel --will-cite --keep-order --max-procs 4 --xargs --results /tmp/super-linter-output/super-linter-worker-results-GIT_COMMITLINT.json --verbose --workdir /github/workspace commitlint --verbose --cwd {} --last --strict`

An interesting observation:
- If I set the correct value for `GITHUB_BEFORE_SHA`, it works [1]. 
- But it seems to me that it's something internal that shouldn't be filled in.

****
[1]
```
      - name: Linter
        uses: super-linter/super-linter@e1cb86b6e8d119f789513668b4b30bf17fe1efe4 # v7.2.0
        env:
          ENABLE_COMMITLINT_STRICT_MODE: true
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          LOG_LEVEL: DEBUG
          GITHUB_BEFORE_SHA: ${{ steps.sha.outputs.commit-sha }}
```

**Comment by 0yi0** [comment]
IMO it's a bug. I tried on a single-commit pull-request and it reported the message.
```
  2024-12-04 13:05:29 [INFO]   Linting GIT_COMMITLINT items...
  Notice: 04 13:05:30 [NOTICE]   GIT_COMMITLINT linted successfully
  2024-12-04 13:05:30 [INFO]   Command output for GIT_COMMITLINT:
  ------
  ⧗   input: Merge 426f9f05ed908db80b2e866c5bc072db56b34456 into 0726f9949efd48a66fd593070f3672409191d0a5
  ✔   found 0 problems, 0 warnings
```
Obviously what was `commitlint`-ted was not my commit message but "Merge {SOME_SHA} into {OTHER_SHA}".

I stole @claudioandre-br's idea with a little bit modification and it worked well for me.

```
      - name: Run super-linter
        uses: super-linter/super-linter/slim@v7.2.0
        env:
          # other envs and
          # work-around for SHA detection
          GITHUB_BEFORE_SHA: ${{ github.event.pull_request.base.sha }}
```

I haven't checked about what will happen on push event.
