### ISSUE TITLE
Error with textlint config (== No rules found, textlint hasn’t done anything ==)

### ISSUE THREAD

**Issue by Falcion** [super-linter/super-linter#6409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Even with default `linttext` config (meaning, created by `--init`) `super-linter` throws an error.

This is `.textlintrc.json`:

```json
{
  "plugins": {},
  "filters": {},
  "rules": {
    "date-weekday-mismatch": true,
    "editorconfig": true,
    "footnote-order": true,
    "no-curly-quotes": true,
    "no-todo": false,
    "period-in-header": true,
    "spelling": {
      "language": "en",
      "skipPatterns": ["JavaScript"],
      "wordDefinitionRegexp": "/[\\w']+/g",
      "suggestCorrections": true
    },
    "terminology": true
  }
}
```

Textlint works perfectly locally, checked with "lint-staged" hooks.

- Required packages for `textlint` (and custom rules) are installed;

### Expected Behavior

Otherwise throw an error of real "textlint" linting result or successful lint.

### Super-Linter version

```markdown
v7.2.0
```

### Super-linter configuration

```yaml
name: Lint
on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null
permissions: {}
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v7.2.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          FILTER_REGEX_EXCLUDE: .*workflows/.*
          LINTER_RULES_PATH: /
          IGNORE_GITIGNORED_FILES: true
          # super-linter doesn't support v9 ESLint
          #JAVASCRIPT_ES_CONFIG_FILE: 'eslint.config.mjs'
          #TYPESCRIPT_ES_CONFIG_FILE: 'eslint.config.mjs'
          JAVASCRIPT_ES_CONFIG_FILE: '.eslintrc.cjs'
          TYPESCRIPT_ES_CONFIG_FILE: '.eslintrc.cjs'
          NATURAL_LANGUAGE_CONFIG_FILE: '.textlintrc.json'
          # We are choosing ESLint and Standard over Prettier
          # because they are more robust and efficient, while prettier stays as the "primitive" base
          # it does not provide advanced settings and etc.
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          # super-linter doesn't support v9 ESLint, reason:
          # Invalid option '--ext' - perhaps you meant '-c'?
          VALIDATE_JSON: false
          FIX_JAVASCRIPT_STANDARD: true
          FIX_TYPESCRIPT_STANDARD: true
```

### Relevant log output

```shell
2024-11-27 12:42:05 [INFO]   Linting NATURAL_LANGUAGE items...
Error: -27 12:42:05 [ERROR]   Found errors when linting NATURAL_LANGUAGE. Exit code: 1.
2024-11-27 12:42:05 [INFO]   Command output for NATURAL_LANGUAGE:
------

== No rules found, textlint hasn’t done anything ==

Possible reasons:
* Your textlint config file has no rules.
* You have no config file and you aren’t passing rules via command line.
* Your textlint config has a syntax error.

=> How to set up rules?
https://github.com/textlint/textlint/blob/master/docs/configuring.md
------
```

### Steps To Reproduce

1. In this environment, with this config, make any push to "trigger" workflow;
2. Wait for the error.

### Anything else?

If helpful, this is the repository's branch on which error occurs:
<https://github.com/Falcion/Patternugit/tree/release/v2.2.0>
