### ISSUE TITLE
Ability to check current commit message in commit-msg hook with commitlint

### ISSUE THREAD

**Issue by gautaz** [super-linter/super-linter#6411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing super-linter from the commit-msg git hook, commitlint always seem to check the previous commit messages, not the current one.

### Expected Behavior

Add a way to check the current commit message when super-linter is executed from the commit-msg git hook.
This way everything could be linted during this hook's execution.

### Anything else?

If this is already possible, perhaps some additional documentation explaining how to do it would be profitable (if it does not already exist, I am the kind of guy failing to see the butter just in front of me in the fridge).

**Comment by ferrarimarco** [comment]
Hi!

Can you please add more context (logs, configurations) so we can have a look at what's going on? Thanks!

**Comment by gautaz** [comment]
The testing environment was:

A commit-msg hook containing the following:

```sh
docker compose run --rm lint-commit
```

A compose file with the following content:

```yaml
services:
  lint-commit:
    image: ghcr.io/super-linter/super-linter:v7.2.0
    environment:
      DEFAULT_BRANCH: "main"
      RUN_LOCAL: "true"
      VALIDATE_CHECKOV: "false"
    volumes:
      - .:/tmp/lint:ro
```

I was expecting that commitlint would lint the commit message of the commit being created during `git commit` but it was in fact linting the previous commit.
I was also wondering how to pass the current commit message (`$1`) to commitlint.
I am most probably missing something to make this work but I guess this is also not necessarily what was intended at first when integrating commitlint.
