### ISSUE TITLE
LINTER_RULES_PATH ignores root dir value

### ISSUE THREAD

**Issue by rodrigobdz** [super-linter/super-linter#6437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

When setting `LINTER_RULES_PATH` to the root directory, I expect it to forget the default value `.github/linters` and search for config files in the root dir instead.

### Expected Behavior

Setting `LINTER_RULES_PATH` to `.` has no effect and linters fail because my config files, like `.pylintrc` are not found in the default dir `.github/linters`. 

### Super-Linter version

```markdown
v7.2.1
```

### Super-linter configuration

```yaml
# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: self-hosted

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.2.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CHECKOV: false
          VALIDATE_BASH_EXEC: false
          PYTHON_PYLINT_CONFIG_FILE: .pylintrc
          LINTER_RULES_PATH: .
          FIX_ENV: true
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
```

### Relevant log output

```shell
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Loading rules for PYTHON_PYLINT...
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Getting linter rules for PYTHON_PYLINT...
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Default rules location: /action/lib/.automation...
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Variable names for language file name: PYTHON_PYLINT_FILE_NAME, language linter rules: PYTHON_PYLINT_LINTER_RULES
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Initializing LANGUAGE_LINTER_RULES value to an empty string...
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Checking if the user-provided:[.pylintrc] and exists at:[/tmp/lint/.github/linters/.pylintrc]
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]     -> Codebase does NOT have file:[/tmp/lint/.github/linters/.pylintrc].
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]     -> Codebase does NOT have file:[/tmp/lint/.github/linters/.pylintrc], using default rules at:[/action/lib/.automation/.pylintrc]
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]     -> Language rules file variable (PYTHON_PYLINT_LINTER_RULES) value is:[/action/lib/.automation/.pylintrc]
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   LANGUAGE_LINTER_RULES_BASENAME: .pylintrc
super-linter-1  | 2024-12-15 13:12:55 [FATAL]     -> PYTHON_PYLINT_LINTER_RULES rules file (/action/lib/.automation/.pylintrc) doesn't exist. Terminating...
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Captured exit code: 1
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Removing temporary files and directories
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   LOG_FILE_PATH: /tmp/lint/super-linter.log
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Skip moving the log file from /tmp/tmp.h65TMWbzxu to /tmp/lint/super-linter.log
super-linter-1  | 2024-12-15 13:12:55 [DEBUG]   Skip moving the private Super-linter output directory (/tmp/super-linter-output) to the output directory (/tmp/lint/super-linter-output/super-linter)
super-linter-1 exited with code 1
```

## Reproduce with GitHub Actions

1. With the `super-linter` config above
2. Commit a Python script with a `line-too-long` issue
3. Ensure that `.pylintrc` ignores this issue
4. `super-linter` fails with `line-too-long` issue

## Reproduce locally

1. Create `compose.yaml` with contents:

    ```yaml
    services:
      super-linter:
        image: ghcr.io/super-linter/super-linter:v7.2.1
        environment:
          - RUN_LOCAL=true
          - LOG_LEVEL=DEBUG
          - DEFAULT_BRANCH=main
          - VALIDATE_CHECKOV=false
          - VALIDATE_BASH_EXEC=false
          - PYTHON_PYLINT_CONFIG_FILE=.pylintrc
          - LINTER_RULES_PATH:.
          - FIX_ENV=true
          - FIX_SHELL_SHFMT=true
          - FIX_YAML_PRETTIER=true
        volumes:
          - .:/tmp/lint
        platform: linux/amd64
    ```

5. Add a `.pylintrc` file with any contents in the root folder
6. Run `super-linter` locally

    ```sh
    docker compose up --remove-orphans --force-recreate
    ```
