### ISSUE TITLE
super-linter does not recognize actionlint.yaml for custom runner labels

### ISSUE THREAD

**Issue by JoaoMJoia** [super-linter/super-linter#6542]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

Description:
When using super-linter/super-linter/slim@v7.2.1, it does not recognize the actionlint.yaml configuration file, causing it to flag self-hosted runner labels as unknown. Despite explicitly defining ubuntu-22.04-4core in actionlint.yaml, the linter continues to throw errors.

Error Message:

```
------
  .github/workflows/*****.yaml:41:14: label "ubuntu-22.04-4core" is unknown. available labels are "windows-latest", "windows-latest-8-cores", "windows-2022", "windows-2019", "ubuntu-latest", "ubuntu-latest-4-cores", "ubuntu-latest-8-cores", "ubuntu-latest-16-cores", "ubuntu-24.04", "ubuntu-22.04", "ubuntu-20.04", "macos-latest", "macos-latest-xl", "macos-latest-xlarge", "macos-latest-large", "macos-15-xlarge", "macos-15-large", "macos-15", "macos-14-xl", "macos-14-xlarge", "macos-14-large", "macos-14", "macos-13-xl", "macos-13-xlarge", "macos-13-large", "macos-13", "macos-12-xl", "macos-12-xlarge", "macos-12-large", "macos-12", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
     |
  41 |     runs-on: ubuntu-22.04-4core
     |              ^~~~~~~~~~~~~~~~~~
  ------
```

May someone help me out here ?

### Expected Behavior

    super-linter should recognize and apply the actionlint.yaml configuration file, preventing the incorrect runner-label error.

### Super-Linter version

```markdown
Super-Linter Version: v7.2.1
    Linter Mode: slim
    Runner Type: ubuntu-latest
    Date: 2025-01-30
```

### Super-linter configuration

```yaml
`      - name: Prepare actionlint config
        run: |
          sudo mkdir -p /action/lib/.automation
          sudo cp .github/linters/actionlint.yaml /action/lib/.automation/actionlint.yaml
          sudo chmod 644 /action/lib/.automation/actionlint.yaml
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.2.1
        env:
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: .github/linters
          LOG_LEVEL: INFO
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_ACTIONS_COMMAND_ARGS: "-shellcheck= -pyflakes="
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yaml-lint.yml
          YAML_ERROR_ON_WARNING: false
          DEFAULT_BRANCH: ${{ inputs.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`
```

### Relevant log output

```shell
Error Message:
`  ------
  .github/workflows/*****.yaml:41:14: label "ubuntu-22.04-4core" is unknown. available labels are "windows-latest", "windows-latest-8-cores", "windows-2022", "windows-2019", "ubuntu-latest", "ubuntu-latest-4-cores", "ubuntu-latest-8-cores", "ubuntu-latest-16-cores", "ubuntu-24.04", "ubuntu-22.04", "ubuntu-20.04", "macos-latest", "macos-latest-xl", "macos-latest-xlarge", "macos-latest-large", "macos-15-xlarge", "macos-15-large", "macos-15", "macos-14-xl", "macos-14-xlarge", "macos-14-large", "macos-14", "macos-13-xl", "macos-13-xlarge", "macos-13-large", "macos-13", "macos-12-xl", "macos-12-xlarge", "macos-12-large", "macos-12", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
     |
  41 |     runs-on: ubuntu-22.04-4core
     |              ^~~~~~~~~~~~~~~~~~
  ------
`
```

### Steps To Reproduce

  1.  Create .github/linters/actionlint.yaml with the following content:

````
---
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - ubuntu-22.04-4core
# Configuration variables in array of strings defined in your repository or
# organization. `null` means disabling configuration variables check.
# Empty array means no configuration variable is allowed.
config-variables: null

# Path-specific configurations
paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'label ".+" is unknown\. available labels are .+'
...
````

2. Set up super-linter in a GitHub Actions workflow:

```
      - name: Prepare actionlint config
        run: |
          sudo mkdir -p /action/lib/.automation
          sudo cp .github/linters/actionlint.yaml /action/lib/.automation/actionlint.yaml
          sudo chmod 644 /action/lib/.automation/actionlint.yaml
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.2.1
        env:
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: .github/linters
          LOG_LEVEL: INFO
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_ACTIONS_COMMAND_ARGS: "-shellcheck= -pyflakes="
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yaml-lint.yml
          YAML_ERROR_ON_WARNING: false
          DEFAULT_BRANCH: ${{ inputs.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

3. Run the workflow and check the logs.

### Anything else?

May someone help me out
