### ISSUE TITLE
EDITORCONFIG_FILE_NAME points to deprecated filename

### ISSUE THREAD

**Issue by TrentBartlem** [super-linter/super-linter#6616]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

With default settings and a `.github/linters/.ecrc` file, warning messages now appear:

    The default configuration file name `.ecrc` is deprecated. Use `.editorconfig-checker.json` instead. You can simply rename it

### Expected Behavior

EDITORCONFIG_FILE_NAME should be set to `.editorconfig-checker.json` by default rather than `.ecrc`. 

editorconfig's [readme](https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#configuration) states:

> The configuration is done via arguments or it will take the first config file found with the following file names:

> .editorconfig-checker.json. 
.ecrc **(deprecated filename, soon unsupported)**

emphasis mine.

### Super-Linter version

```markdown
v7.3.0
```

### Super-linter configuration

```yaml
# note: 
# /.github/linters/.ecrc must exist
# /.editorconfig must exist

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      packages: read
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: "super-linter/super-linter@v7" # can be v7.3.0 if you prefer
        env:
          VALIDATE_EDITORCONFIG: true
```

### Relevant log output

```shell
------
Error: -27 00:18:27 [ERROR]   Errors found in EDITORCONFIG
Error: -27 00:18:27 [ERROR]   Stdout contents for EDITORCONFIG:
------
The default configuration file name `.ecrc` is deprecated. Use `.editorconfig-checker.json` instead. You can simply rename it
Error: -27 00:18:30 [ERROR]   Super-linter detected linting errors
super-linter-output/super-linter-summary.md 57ms
```

### Steps To Reproduce

create minimal /.github/linters/.ecrc
create minimal /.editorconfig
run super-linter over a codebase with VALIDATE_EDITORCONFIG: true
see warning 

### Anything else?

https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#configuration
