### ISSUE TITLE
XML validation output is too verbose

### ISSUE THREAD

**Issue by thomasleplus** [super-linter/super-linter#6653]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

Hi,

I am running the image `super-linter/super-linter:latest` and I noticed for a while that the output of the XML validation tool is very verbose. Basically it seems to output the whole content of the validated XML files even when no issue is found. This is flooding my CI/CD logs and I think that it could also be a security concern if any of my XML files contained some sensitive data that I don't want to leak into the CI/CD logs.

The output looks like this in my logs:

```text
2025-03-10 03:05:30 [INFO]   Linting XML items...
2025-03-10 03:05:30 [NOTICE]   XML linted successfully
2025-03-10 03:05:30 [INFO]   Command output for XML:
------
<?xml version="1.0" encoding="UTF-8"?>
...
```

Please let me know if there is an option to disable this behavior? Otherwise I think there should be such an option and it should probably be disabled by default IMHO.

Cheers,

Thomas

### Expected Behavior

When no issue is found, the log should just say:

```text
2025-03-10 03:05:30 [INFO]   Linting XML items...
2025-03-10 03:05:30 [NOTICE]   XML linted successfully
2025-03-10 03:05:31 [INFO]   Linting YAML items...
```

### Super-Linter version

```markdown
v7.3.0
```

### Super-linter configuration

```yaml
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: true
          LINTER_RULES_PATH: .
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Relevant log output

```shell
2025-03-10 03:05:30 [INFO]   Linting XML items...
2025-03-10 03:05:30 [NOTICE]   XML linted successfully
2025-03-10 03:05:30 [INFO]   Command output for XML:
------
<?xml version="1.0" encoding="UTF-8"?>
```

### Steps To Reproduce

Use the GitHub Actions configuration above on any GitHub repo containing XML files.
