### ISSUE TITLE
Ansible validation generating ".ansible" causing other linter failures

### ISSUE THREAD

**Issue by neilime** [super-linter/super-linter#6713]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

When running superlinter against an ansible directory (located in `./ansible`), it is creating some folder and files in `./ansible/.ansible` (it is downloading the roles by example - `ansible/.ansible/roles/Oefenweb.ssh_keys`)

Those files are causing linter issues. Example:

```
Clone found (markdown):
 - /local-path/ansible/.ansible/roles/Oefenweb.ssh_keys/LICENSE.txt [1:1 - 19:10] (18 lines, 333 tokens)
   /local-path/ansible/.ansible/roles/Oefenweb.yarn/LICENSE.txt [1:1 - 19:10]
```

I've tried many solutions without success:
- to gitignore those files and pass the env var `IGNORE_GITIGNORED_FILES=true`
- Ignore those files with env var `FILTER_REGEX_EXCLUDE="^ansible/.ansible/"`
- Using different images and versions: 
  - `ghcr.io/super-linter/super-linter:latest`
  - `ghcr.io/super-linter/super-linter:slim-latest`
  - `ghcr.io/super-linter/super-linter:v7.3.0`
  - `ghcr.io/super-linter/super-linter:slim-v7.3.0`

I've tried to change the ansible config:
- Changing `roles_path = /etc/ansible/roles`
- Changing `home = /etc/ansible`

This issue is because of ansible lint storing some cache in this `.ansible` folder using `ansible_compat.get_cache_dir`.

- https://github.com/ansible/ansible-lint/blob/6a4fcdb135dd2be6e8ee5ddb5bf59d3d78cbe7b0/src/ansiblelint/__main__.py#L139
- https://ansible.readthedocs.io/projects/compat/api/#ansible_compat.prerun

In my opinion this folder should be ignored

### Expected Behavior

The generated `.ansible` folder should not be parsed by linter

### Super-Linter version

```markdown
- latest
- slim-latest
- v7.3.0
- slim-v7.3.0
```

### Super-linter configuration

```yaml
Locally with docker: 

`docker run -e DEFAULT_WORKSPACE="$(pwd)" -e IGNORE_GITIGNORED_FILES=true -v "$(pwd):/local-workspace" --rm ghcr.io/super-linter/super-linter:slim-v7

With github action:


- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

- uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
  env:
    VALIDATE_ALL_CODEBASE: true
    LOG_LEVEL: WARN
    DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    GITHUB_TOKEN: ${{ github.token }}
```

### Relevant log output

```shell
2025-04-01 20:54:12 [ERROR]   Stdout contents for JSCPD:
------
Clone found (markdown):
 - /local-workspace/ansible/.ansible/roles/Oefenweb.ssh_keys/LICENSE.txt [1:1 - 19:10] (18 lines, 333 tokens)
   /local-workspace/ansible/.ansible/roles/Oefenweb.yarn/LICENSE.txt [1:1 - 19:10]
```

### Steps To Reproduce

1. Create an ansible folder with some playbook and requirements
```
ansible
|- requirements.txt
|- test.yml
```
2. Add roles requirements to `requirements.txt`
```txt
roles:
  - src: Oefenweb.yarn
    version: v1.0.57
  - src: Oefenweb.ssh_keys
    version: v5.0.5
```

3. Create playbook to `test.yml`

```yml
---
- hosts: all
  roles:
    - oefenweb.yarn
    - Oefenweb.ssh_keys
```

4. Run super-linter
5. There should have some JSCP issues on `ansible/.ansible/...` files

### Anything else?

Live example in github action workflow: https://github.com/neilime/ubuntu-config/actions/runs/14203685546/job/39796291069
