### ISSUE TITLE
JSCPD_CONFIG_FILE causing issues

### ISSUE THREAD

**Issue by AR-FF** [super-linter/super-linter#6734]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

If you do not provide the jscpd_config_file, it works fine but doesn't using a custom path doesn't work

### Expected Behavior

I would expect the file at the root to work or to pass it an appropriate file

### Super-Linter version

```markdown
v7.3.0
```

### Super-linter configuration

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          JSCPD_CONFIG_FILE: ${{ env.working_dir || github.workspace }}/.jscpd.json
```

### Relevant log output

```shell
2025-04-24 15:47:18 [FATAL]     -> JSCPD_LINTER_RULES rules file (/action/lib/.automation//github/workspace/.jscpd.json) doesn't exist. Terminating...
```

### Steps To Reproduce

Add the action to your pipeline

### Anything else?

I was trying to figure out where the original reference was in my code but it seems to be called out in the source's tests: https://github.com/super-linter/super-linter/blob/befeed0a95963976c3fcdd765f002f0677c64a6c/test/inspec/super-linter/controls/super_linter.rb#L516
