### ISSUE TITLE
nbQA configuration not taking effect

### ISSUE THREAD

**Issue by matous-volf** [super-linter/super-linter#6736]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

Adding the .jupyter-nbqa.toml file to `.github/linters`, according to [`TEMPLATES/.jupyter-nbqa.toml`](https://github.com/super-linter/super-linter/blob/befeed0a95963976c3fcdd765f002f0677c64a6c/TEMPLATES/.jupyter-nbqa.toml), and editing it does not influence the behavior. For instance, I have added the following:

```toml
[tool.nbqa.addopts]
flake8 = ["--extend-ignore=E203,E501,E731"]

[tool.ruff]
ignore = ["E731"]
```

Adding this to `pyproject.toml` in the project root does work.

### Expected Behavior

I may be wrong, but I suppose the `.jupyter-nbqa.toml` file should be used with the same format as the `pyproject.toml`, as described in the [nbQA docs](https://nbqa.readthedocs.io/en/latest/configuration.html).

### Super-Linter version

```markdown
7.3.0
```

### Super-linter configuration

```yaml
- name: checkout code
        uses: actions/checkout@v4
        with:
          # Super-linter needs the full git history to get the list of files that changed across commits
          fetch-depth: 0
      - name: Super-linter check
        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
        env:
          # to report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          FIX_YAML_PRETTIER: true
          VALIDATE_CSS: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          VALIDATE_YAML: false
          VALIDATE_JSCPD: false
          VALIDATE_PYTHON_ISORT: false
```

### Relevant log output

```shell
none
```

### Steps To Reproduce

[This commit](https://github.com/matous-volf/political-leaning-prediction/pull/55/commits/76ef4846388218cef61c1b057d77deb3871270cb) (with the `.jupyter-nbqa.toml`) does not pass the checks – the config is not used – [this one](https://github.com/matous-volf/political-leaning-prediction/pull/55/commits/beefa3bc39ddc29ff2836591046c76a6199b3060) (with the `pyproject.toml` added to the root) does pass – the config is used.
