### ISSUE TITLE
Commitlint config file detected only if in root path

### ISSUE THREAD

**Issue by streambinder** [super-linter/super-linter#6799]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

If I place `commitlint.config.js` in .github/linters, super-linter is not able to find it, resulting in commitlint linter disablement.
It only works correctly if I place such config file in the root of the repository.

### Expected Behavior

As for any other linter config, I think the commitlint config file should rather be located in .github/linters path as well.

### Super-Linter version

```markdown
v7.4.0
```

### Super-linter configuration

```yaml
super-linter:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: super-linter/super-linter/slim@v7.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: ${{ !contains(github.event_name, 'pull_request') }}
```

### Relevant log output

```shell
[...]
2025-05-20 11:27:12 [WARN]    Git commit message validation with commitlint is enabled, but no commitlint configuration file is available. Disabling commitlint. To suppress this message, either disable Git commit validation by setting VALIDATE_GIT_COMMITLINT to false in your Super-linter configuration, or provide a commitlint configuration file.
[...]
```

### Steps To Reproduce

Run super-linter with `commintlint.config.js` config file in .github/linters.
