### ISSUE TITLE
JmesPath Error for json_query functions in an ansible lint

### ISSUE THREAD

**Issue by johnpetersjr** [super-linter/super-linter#6803]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

We are upgrading our usage of super-linter from 5.6.1 to 7.4.0, and our ansible files that used to pass a linting check just fine are no longer working in the latest version.  I feel like we may have found an interesting bug?

Here are two ansible plays, they both pass linting in the old version, but in the new version, only the second one fails:
```
- name: Working Ansible Play 1
  ansible.builtin.debug:
    msg: "{{ list_output }}  id= {{ list_output | json_query('privateendpoints[0].id') }} "

- name: Failing Ansible Play 2
  ansible.builtin.set_fact:
    found_nic: "{{ list_output | json_query('privateendpoints[0].network_interfaces[0]') }}"
```

My gut feeling is that perhaps the linter doesn't like the evaluating a json_query string that ends in an array without a .id (or some sort of .variable) at the end of the json object it's looking at?

This could very well be an ansible-lint problem, and not a superlinter issue, but thought I would bring it up here to see if anyone else has experienced the same problem.

The error we get on the failing ansible play 2 is:
```
[jinja[invalid]: roles/my_ansible_role/tasks/main.yml#Lxxx](https://github.com/<snip>/pull/6666/files#annotation_numbershere)
You need to install "jmespath" prior to running json_query filter
```

### Expected Behavior

I would expect the ansible plays that passed fine in the old version to continue to pass without issue in the latest super linter version.

### Super-Linter version

```markdown
v7.4.0
```

### Super-linter configuration

```yaml
---
name: Lint Code Base
on:
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: Superlinter
    runs-on: ubuntu-24.04 # we also tried ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.4.0
        env:
          VALIDATE_ALL_CODEBASE: false
          ANSIBLE_CONFIG_FILE: .ansible-lint
          ANSIBLE_DIRECTORY: "."
          BASH_SEVERITY: "error"
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPPRESS_POSSUM: true
          VALIDATE_BASH: false
          VALIDATE_GITLEAKS: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_CHECKOV: false
          VALIDATE_YAML_PRETTIER: false
          ADDITIONAL_REQUIREMENTS_FILE: .github/linters/requirements.txt
          VALIDATE_NATURAL_LANGUAGE: false
          YAML_CONFIG_FILE: .yamllint.yml
```

### Relevant log output

```shell
n/a
```

### Steps To Reproduce

n/a
