### ISSUE TITLE
Error 500 when configuring ansible linter

### ISSUE THREAD

**Issue by amedee** [super-linter/super-linter#6846]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [x] I am using the latest Super-linter version.
- [x] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [x] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [x] I think that this is a Super-linter issue.

### Current Behavior

When configuring Ansible linter:
Error when getting available collection versions for community.docker from default (https://galaxy.ansible.com/api/) (HTTP Code: 500, Message: Internal Server Error Code: Unknown)

### Expected Behavior

I expect no errors to be found.

### Super-Linter version

```markdown
v7.4.0 commit 12150456a73e248bdc94d0794898f94e23127c88
```

### Super-linter configuration

```yaml
jobs:
  lint:
    name: Super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Cache Ansible roles and collections
        uses: actions/cache@v4
        with:
          path: |
            .ansible/roles
            .ansible/collections
          key: ansible-deps-v1

      - name: Pre-install Ansible Galaxy roles (with retry)
        run: |
          set -x
          for i in {1..5}; do
            if ansible-galaxy install -vv -r requirements.yml; then
              break
            else
              echo "Installation failed, retry in $((i * 10)) seconds…" >&2
              sleep $((i * 10))
            fi
          done

      - name: Run Super-linter
        # yamllint disable-line rule:line-length
        uses: super-linter/super-linter/slim@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0
        env:
          ANSIBLE_DIRECTORY: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_PYTHON_PYINK: false
          FIX_YAML_PRETTIER: true
```

### Relevant log output

```shell
Super-Linter initialization
2025-06-16 15:25:25 [INFO]   Command output when running linters:
------
ANSIBLE
  2025-06-16 15:03:12 [INFO]   Linting ANSIBLE items...
  Error: -16 15:24:51 [ERROR]   Found errors when linting ANSIBLE. Exit code: 2.
  2025-06-16 15:24:51 [INFO]   Stderr contents for ANSIBLE:
  ------
  ERROR    ERROR! Error when getting available collection versions for community.docker from default (https://galaxy.ansible.com/api/) (HTTP Code: 500, Message: Internal Server Error Code: Unknown)
  
  Got 1 exit code while running: ansible-galaxy collection install -r /github/workspace/requirements.yml
  ------
BASH
BASH_EXEC
CHECKOV
GITHUB_ACTIONS
GITLEAKS
GIT_MERGE_CONFLICT_MARKERS
JSCPD
MARKDOWN
MARKDOWN_PRETTIER
NATURAL_LANGUAGE
PYTHON_BLACK
PYTHON_PYLINT
PYTHON_FLAKE8
PYTHON_ISORT
PYTHON_MYPY
PYTHON_RUFF
SHELL_SHFMT
YAML
YAML_PRETTIER
------
2025-06-16 15:25:25 [INFO]   ----------------------------------------------
2025-06-16 15:25:25 [INFO]   ----------------------------------------------
Error: -16 15:25:25 [ERROR]   Errors found in ANSIBLE
Notice: 16 15:25:25 [NOTICE]   Successfully linted BASH
Notice: 16 15:25:26 [NOTICE]   Successfully linted BASH_EXEC
Notice: 16 15:25:26 [NOTICE]   Successfully linted CHECKOV
Notice: 16 15:25:26 [NOTICE]   Successfully linted GITHUB_ACTIONS
Notice: 16 15:25:27 [NOTICE]   Successfully linted GITLEAKS
Notice: 16 15:25:27 [NOTICE]   Successfully linted GIT_MERGE_CONFLICT_MARKERS
Notice: 16 15:25:27 [NOTICE]   Successfully linted JSCPD
Notice: 16 15:25:28 [NOTICE]   Successfully linted MARKDOWN
Notice: 16 15:25:28 [NOTICE]   Successfully linted MARKDOWN_PRETTIER
Notice: 16 15:25:28 [NOTICE]   Successfully linted NATURAL_LANGUAGE
Notice: 16 15:25:28 [NOTICE]   Successfully linted PYTHON_BLACK
Notice: 16 15:25:29 [NOTICE]   Successfully linted PYTHON_PYLINT
Notice: 16 15:25:29 [NOTICE]   Successfully linted PYTHON_FLAKE8
Notice: 16 15:25:29 [NOTICE]   Successfully linted PYTHON_ISORT
Notice: 16 15:25:29 [NOTICE]   Successfully linted PYTHON_MYPY
Notice: 16 15:25:30 [NOTICE]   Successfully linted PYTHON_RUFF
Notice: 16 15:25:30 [NOTICE]   Successfully linted SHELL_SHFMT
Notice: 16 15:25:31 [NOTICE]   Successfully linted YAML
Notice: 16 15:25:31 [NOTICE]   Successfully linted YAML_PRETTIER
Error: -16 15:25:31 [ERROR]   Super-linter detected linting errors
```

### Steps To Reproduce

This is my `requirements.yml`:

```yaml
---
roles:
  - name: geerlingguy.munin-node
    version: 1.4.0
  - name: rolehippie.swap
    version: v2.0.0

collections:
  - name: amazon.aws
    version: 10.1.0
  - name: ansible.posix
    version: 2.0.0
  - name: community.docker
    version: 4.6.1
  - name: community.general
    version: 10.7.0
  - name: community.mysql
    version: 3.14.0
  - name: debops.debops
    version: 3.2.4
```
